### ISSUE TITLE
Files in MANIFEST.in not included in the installation

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder-notebook#101]
Add to `setup.py`  > `include_package_data=True`

**Comment by ccordoba12** [comment]
Why is this needed? Our wheels went without data files (i.e. svg, html and ipynb)?

**Comment by dalthviz** [comment]
Yep, when trying `pip install spyder-notebook` the `welcome.html` couldn't be found:

![imagen](https://user-images.githubusercontent.com/16781833/29000725-32bd99ba-7a3a-11e7-9246-07a2cbc919f2.png)

**Comment by ccordoba12** [comment]
Gosh, Python packaging is hell!

We need to release 0.1.1 as soon as possible.

**Comment by ccordoba12** [comment]
Please try to this tomorrow to not have a broken package around.
