### ISSUE TITLE
limitation on spyder-notebook (or error from me ?)

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder-notebook#104]
I can't get the moviepy initial example working inside spyder_notebook.

Is there a limitation somewhere ?
````
from moviepy.editor import *
# with http://techslides.com/demos/sample-videos/small.mp4
clip = VideoFileClip("small.mp4").rotate(90)
clip.ipython_display()
````
expected (jupyter notebook standard):
 
![moviepy_in_jupyter](https://user-images.githubusercontent.com/4312421/29002409-6a98745a-7aa2-11e7-8681-b809b43c692d.PNG)

result (re-opening and playing the same notebook in spyder-notebook):
![moviepy_in_spyder-notebook](https://user-images.githubusercontent.com/4312421/29002440-01ab57fe-7aa3-11e7-97f7-91d632c6a5bc.PNG)

**Comment by rlaverde** [comment]
I think this is a limitation, probably the web engine of Qt doesn't support some html5 stuff that is used for display that result.

Are you using pyqt4? I think you could expect better results using qt5 as the qt web engine won't be outdated too much. http://doc.qt.io/qt-5/qtwebengine-overview.html

**Comment by stonebig** [comment]
I'm using PyQt5-5.9.0

**Comment by dalthviz** [comment]
Maybe this link is relevant here http://doc.qt.io/qt-5/qtwebengine-features.html#audio-and-video-codecs

**Comment by ccordoba12** [comment]
@dalthviz, I think @dalthviz is right: this seems to depend on how Qt was compiled (something we know nothing about it).

**Comment by stonebig** [comment]
ah, ok. Thanks for the explanation.
