### ISSUE TITLE
Conda install is not working

### ISSUE THREAD

**Issue by petrosb** [spyder-ide/spyder-notebook#108]
Seems the conda package does not exist (yet?). Here is the output:

bash-3.2$ conda install spyder-notebook -c spyder-ide
Fetching package metadata .............

PackageNotFoundError: Packages missing in current channels:
            
  - spyder-notebook

We have searched for the packages in the following channels:
            
  - https://conda.anaconda.org/spyder-ide/osx-64
  - https://conda.anaconda.org/spyder-ide/noarch
  - https://conda.anaconda.org/intel/osx-64
  - https://conda.anaconda.org/intel/noarch
  - https://repo.continuum.io/pkgs/free/osx-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/osx-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/osx-64
  - https://repo.continuum.io/pkgs/pro/noarch

**Comment by ccordoba12** [comment]
@dalthviz, please fix this.

**Comment by dalthviz** [comment]
@petrosb please try with `conda install -c conda-forge spyder-notebook` we will add Spyder notebook to the `spyder-ide` channel soon.

**Comment by dalthviz** [comment]
Now the `spyder-ide` channel has the package 🎉

![imagen](https://user-images.githubusercontent.com/16781833/29103102-413f71fc-7c83-11e7-9ad6-f68dc84afeb8.png)

**Comment by ccordoba12** [comment]
Great! Thanks @dalthviz!
