### ISSUE TITLE
Server error because it takes too much time to start

### ISSUE THREAD

**Issue by Diego-MX** [spyder-ide/spyder-notebook#113]
Thank you for the development of the Spyder Notebooks.  I am excited to use it out in my projects.  

Unfortunately I'm getting a Server error about Jupyter from within Spyder, it goes like this:  
```
The Jupyter Notebook server failed to start or it is taking too much time to do it.  Please start it in a system terminal with the command 'jupyter notebook' to check for errors.  
```

The error is strange because it only happens from within Spyder.  If I just run the notebook it works fine.  
And more so, it happens when I run it from a specific environment that we use at work.  
How can I search which dependencies from the environment trigger the error in Spyder?  

Thanks again.

**Comment by dalthviz** [comment]
Hi @Diego-MX could you provide the packages list of the env where you are facing this problem?. Maybe you can test creating a new env and add, package by package, the ones that are in the specific env where the problem arise.

**Comment by xgnata** [comment]
I have the same issue with WinPython-64bit-3.6.2.0Qt5
The list of packages is here https://github.com/winpython/winpython/blob/master/changelogs/WinPythonQt5-64bit-3.6.2.0.md
What else do you need?

"it happens when I run it from a specific environment that we use at work." I'm also at work. I will test at home. It may be related to firewall settings.

Why is spyder trying to launch a Jupyter Notebook altogether?? Is it the new way ipython works?

**Comment by xgnata** [comment]
The error read "please start a terminal with the command 'jupyter notebook' to check for errors.
I did that and it works meaning that the notebook starts. However, it is complaining about the port 8888 being used....but it uses the port 8889 automatically and it works.

[I 15:26:40.194 NotebookApp] The port 8888 is already in use, trying another port.
[I 15:26:40.275 NotebookApp] JupyterLab alpha preview extension loaded from C:\Users\gnata\Documents\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-pack
ages\jupyterlab
JupyterLab v0.26.5
Known labextensions:
   app dir: C:\Users\gnata\Documents\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd
64\share\jupyter\lab
        @jupyter-widgets/jupyterlab-manager@0.25.11 enabled  ok
[W 15:26:40.305 NotebookApp] Build required: Installed extensions changed
[E 15:26:40.308 NotebookApp] shemas_dir: C:\Users\gnata\Documents\WinPython-64bi
t-3.6.2.0Qt5\python-3.6.2.amd64\share\jupyter\lab\schemas
[I 15:26:41.038 NotebookApp] Serving notebooks from local directory: C:\Users\gn
ata\Documents\WinPython-64bit-3.6.2.0Qt5
[I 15:26:41.038 NotebookApp] 0 active kernels
[I 15:26:41.039 NotebookApp] The Jupyter Notebook is running at:
[I 15:26:41.039 NotebookApp] http://localhost:8889/?token=0071f2269b7957d0467cc1
ce2ef7589b7e2c11824a9387bf
[I 15:26:41.040 NotebookApp] Use Control-C to stop this server and shut down all
 kernels (twice to skip confirmation).
[C 15:26:41.044 NotebookApp]
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8889/?token=0071f2269b7957d0467cc1ce2ef7589b7e2c11824a9387bf
[I 15:26:42.655 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1

**Comment by ccordoba12** [comment]
@dalthviz, I think we need to increase the time to check if the server is up or not.

**Comment by dalthviz** [comment]
ok :+1: @ccordoba12 , @xgnata  could you see if increasing the number for `range` on this [line](https://github.com/spyder-ide/spyder-notebook/blob/master/spyder_notebook/utils/nbopen.py#L89) in your installation helps?

Another option you may try could be to change your default port for the [server](https://stackoverflow.com/questions/40373330/change-jupyter-notebooks-localhost8888-default-server-with-other) to see if that decreases the time for the server to start.

**Comment by xgnata** [comment]
I have increased the timeout from 40*0.25 to 100*0.25 and I don't see the
error anymore. Changing the port does not speed up the start process (or it
is not significant on my machine).
Once spyder has started I get 3 times the message 'the kernel is dead,
retarted' in the iPhone window but then everything works (I get a working
iPhone console). Is it 'normal'? It not a very nice user experience.

Le 5 oct. 2017 2:55 AM, "Daniel Althviz Moré" <notifications@github.com> a
écrit :

**Comment by ccordoba12** [comment]
> Is it 'normal'? It not a very nice user experience.

Yes, it is normal, but we're working to not show those message in Spyder 3.2.4

**Comment by xgnata** [comment]
OK. As it takes quite some time to start spyder on some machines, it would
be good to splash the startup image as soon as possible in the start
process. As it is now i see people includibg myself more than double
clicking on the icon because 'nothing happens'. Is results in several
spyder instances opened after many one minute lag or so.

Le 5 oct. 2017 2:24 PM, "Carlos Cordoba" <notifications@github.com> a
écrit :

**Comment by precabal** [comment]
hey, thanks for this fix! however, the conda package is still in the prior version so I'm getting the error after a fresh install (which installed 0.1.1)
how can I install the latest release? I'm new to anaconda and I understand the use of pip is discouraged... but I'm sure there must be a proper way to handle this issue.
