### ISSUE TITLE
Template for the reports of issues

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder-notebook#122]

**Comment by ccordoba12** [comment]
@dalthviz, what do you mean by this?

**Comment by dalthviz** [comment]
@ccordoba12 I mean [this](https://help.github.com/articles/creating-an-issue-template-for-your-repository/), the template you see when opening a new issue. In order to have more info when a initial issue is created (stuff like the Spyder version, Jupyter notebook version, steps to reproduce the issue, maybe a screenshot, etc), or maybe it's not needed?

**Comment by ccordoba12** [comment]
> maybe it's not needed?

Sure, it's a good idea!
