### ISSUE TITLE
how to open a path that contain multiple notebook??

### ISSUE THREAD

**Issue by adaaaaaa** [spyder-ide/spyder-notebook#127]
i know one usage is to open a single notebook, but i don't know how to open a path...
anybody know how to do ?

**Comment by ccordoba12** [comment]
This is not possible right now, sorry. You need to open all notebooks one by one.

@dalthviz, could we do something about it?

**Comment by dalthviz** [comment]
@ccordoba12 I'm not quite sure to understand this one, @adaaaaaa if you want to open more than one notebook at the same time you could select all the notebooks you want from a directory like this:

![nnotebooks](https://user-images.githubusercontent.com/16781833/31743640-65685c9e-b421-11e7-86fe-d32596cf3022.gif)

**Comment by ccordoba12** [comment]
Good suggestion @dalthviz!

@adaaaaaa, I think this solves your problem, right?

**Comment by adaaaaaa** [comment]
no... i mean like this ... @ccordoba12 @dalthviz 
![tree](https://user-images.githubusercontent.com/23206387/31750355-174d79a4-b4b2-11e7-9183-badadac6f5ba.png)

**Comment by ccordoba12** [comment]
We don't provide that, sorry. We'll try to integrate this plugin with Spyder's file explorer in the future, though.
