### ISSUE TITLE
UnicodeDecodeError after closing a notebook

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-notebook#128]
@ioodufow commented on [Fri Oct 20 2017](https://github.com/spyder-ide/spyder/issues/5516)

## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\2PAC\Anaconda3\lib\site-packages\spyder_notebook\notebookplugin.py", line 359, in close_client
    nb_contents = nbformat.read(path, as_version=4)
  File "C:\Users\2PAC\Anaconda3\lib\site-packages\nbformat\__init__.py", line 139, in read
    return read(f, as_version, **kwargs)
  File "C:\Users\2PAC\Anaconda3\lib\site-packages\nbformat\__init__.py", line 141, in read
    return reads(fp.read(), as_version, **kwargs)
  File "C:\Users\2PAC\Anaconda3\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.2.0 (NOK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  

---

@ccordoba12 commented on [Fri Oct 20 2017](https://github.com/spyder-ide/spyder/issues/5516#issuecomment-338223133)

Thanks for reporting. This is a bug in `spyder-notebook`, so I'm moving this issue to its corresponding repo.

**Comment by dalthviz** [comment]
Hi @ioodufow could you please provide us the notebook and path of the file in your system, that you were running when this problem appeared?

**Comment by ioodufow** [comment]
Hello! Do you want to login to my system?
Why do you need the path?

**Comment by dalthviz** [comment]
It's just to know if there is any strange character that could cause a `UnicodeDecodeError`. 

There is no need to login in your system :)

**Comment by jitseniesen** [comment]
Closing because no further information was given.
