### ISSUE TITLE
How to install on Windows 7?

### ISSUE THREAD

**Issue by mas-dse-dhpancha** [spyder-ide/spyder-notebook#130]
Hi,

I notice that the installation instructions for the ipynb plugin on Spyder are for linux or Mac. I was wondering if you can install in on a Windows machine? Thanks.

**Comment by dalthviz** [comment]
Hi @mas-dse-dhpancha you can install the plugin by runnig the same commands with `cmd` (or the `Anaconda prompt` in case you use an `Anaconda`):

if you use `pip` you can use:
```
pip install spyder-notebook
```
if you use `Anaconda` you can use in `cmd` or the `Anaconda prompt`:
```
conda install spyder-notebook -c spyder-ide
```

**Comment by ccordoba12** [comment]
@mas-dse-dhpancha, the instructions are valid for all operating systems.
