### ISSUE TITLE
cannot open jupyter notebook

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-notebook#139]
@Khalilsqu commented on [Fri Dec 08 2017](https://github.com/spyder-ide/spyder/issues/5921)

## Description

**What steps will reproduce the problem?**

1. cannot open new or existing ipnb files
404 : Not Found
You are requesting a page that does not exist!

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Anaconda3\lib\site-packages\spyder_notebook\notebookplugin.py", line 372, in close_client
    client.shutdown_kernel()
  File "C:\Anaconda3\lib\site-packages\spyder_notebook\widgets\client.py", line 236, in shutdown_kernel
    kernel_id = self.get_kernel_id()
  File "C:\Anaconda3\lib\site-packages\spyder_notebook\widgets\client.py", line 222, in get_kernel_id
    sessions = json.loads(sessions_req)
  File "C:\Anaconda3\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Anaconda3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.9.2, PyQt5 5.9.1 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.

---

@Khalilsqu commented on [Fri Dec 08 2017](https://github.com/spyder-ide/spyder/issues/5921#issuecomment-350235380)

sorry, it is working wight now, thanks alot, appreciate your help and support and very happy this this ide

---

@CAM-Gerlach commented on [Fri Dec 08 2017](https://github.com/spyder-ide/spyder/issues/5921#issuecomment-350314788)

Thanks for reporting, and good to hear. If the problem was resolved, then feel free to close this issue.

**Comment by dalthviz** [comment]
@ccordoba12 should we close this one?

**Comment by ccordoba12** [comment]
Sure, closing due to lack of response.

**Comment by JasonVon** [comment]
I have faced the same issue repeatedly once I tried to open a notebook file (.ipynb). Is there any solution now? Thanks.

**Comment by dalthviz** [comment]
Hi @JasonVon since there was no more feedback we didn't dig more around this. If you want, you can add here info to replicate the problem (the steps to reproduce the issue, the version of the dependencies that you are using, etc). Any information in order to replicate the problem is gratly appreciated

**Comment by mmagnuski** [comment]
I have the same problem on one of the classroom computers (windows 10). The error appears as soon as spyder opens, then IPython kernal fails to connect (neverending *connecting to kernel...*) and notebook tab is all gray.
`show details` gives me:
```
    plugin.register_plugin()
    self.create_new_client(give_focus=False)
    server_info = nbopen(filename)
    server_info = find_best_server(filename)
    servers = [si for si in notebookapp.list_running_servers()
    servers = [si for si in notebookapp.list_running_servers()
    info = json.load(f)
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
    return _default_decoder.decode(s)
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Versions:
```
# Name                    Version                   Build  Channel
spyder                    3.3.1                    py36_1
spyder-kernels            0.2.4                    py36_0
spyder-notebook           0.1.3                    py36_0    spyder-ide
jupyter                   1.0.0                    py36_7
jupyter_client            5.2.3                    py36_0
jupyter_console           5.2.0            py36h6d89b47_1
jupyter_core              4.4.0                    py36_0
jupyterlab                0.27.0           py36h34cc53b_2
jupyterlab_launcher       0.4.0            py36h22c3ccf_0
notebook                  5.7.0                    py36_0
```
