### ISSUE TITLE
how to manually install 

### ISSUE THREAD

**Issue by paulga** [spyder-ide/spyder-notebook#140]
Due to user privileges reason, I want to know if it's possible to manually place the unzipped files into some folder

## Description of your problem

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**

## Versions and main components

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Jupyter Notebook Version:
* Operating system:

windows 7

For 
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by dalthviz** [comment]
Hi @paulga you could try to put the `spyder_notebook` folder of the plugin in `C:\Users\<your_user>\.spyder-py3\plugins` (after restarting Spyder you should be able to see the plugin in Spyder).

The structure of folders should be something like:

```cmd
---/.spyder-py3
-----------------/plugins
--------------------------/spyder_notebook
------------------------------------------/images
------------------------------------------/test
------------------------------------------/utils
------------------------------------------/widgets
------------------------------------------/__init__.py
------------------------------------------/_version.py
------------------------------------------/notebookplugin.py
```

Also take into account that you will need the dependencies of the plugin installed (`spyder>=3.2.0`, `notebook>=4.3`, `qtpy`, `requests`, `psutil`, `nbformat`)

**Comment by paulga** [comment]
my installation is Anaconda (spyder is part of it), so I don't have a .spyder-py3 folder. 
Can you manually install this plugin for Anaconda?

**Comment by dalthviz** [comment]
And what about a `.spyder` folder?. If you are using Python 2 you should find `.spyder`. If you are using Python 3 it should be `.spyder-py3`. These folders are created by Spyder (for the config of settings you see from Spyder) with or without a installation from the Anaconda distribution. Are you sure you can't find anywhere one of this folders?

**Comment by paulga** [comment]
I cannot see a .spyder folder. the Anaconda I installed uses Python 2.7.

**Comment by dalthviz** [comment]
Since your problem is with user privileges you could try to install Anaconda for your user only (without admin priviliges) and use Anaconda prompt from that version to install the plugin with `conda install spyder_notebook`.

**Comment by paulga** [comment]
running "cmd“ is also prevented

**Comment by dalthviz** [comment]
Then you could try to do the installation in your user of Anaconda, then find in your user the `.spyder` folder (if you install the version of Anaconda with Python 2.7) and do the above. If you can't find the `.spyder` folder I'm affraid there is nothing you can do to install the plugin :/
