### ISSUE TITLE
can it support markdown file?

### ISSUE THREAD

**Issue by adaaaaaa** [spyder-ide/spyder-notebook#147]
i have two kind of file containing some tutorial...
they are .ipynb and .md file...
can spyder-notebook support .md file?

**Comment by ccordoba12** [comment]
spyder-notebook simply embeds the Jupyter notebook inside a Spyder pane, so it can't do more than the notebook does.

If you want to edit and render markdown files, please take a look at [spyder-reports](https://github.com/spyder-ide/spyder-reports).
