### ISSUE TITLE
Error when loading a notebook

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-notebook#149]
@KrunalDatascience commented on [Wed May 23 2018](https://github.com/spyder-ide/spyder/issues/7182)

 

Saved the notebook from spyder. It didn't load post saving. And now tried opened it through spyder-notebook it is not loading and the screen got hanged.

---

@ccordoba12 commented on [Wed May 23 2018](https://github.com/spyder-ide/spyder/issues/7182#issuecomment-391338698)

Moving to the right repo.

**Comment by ccordoba12** [comment]
> It didn't load post saving

@KrunalDatascience, what do you mean by this?

**Comment by jitseniesen** [comment]
Closing due to lack of information.
