### ISSUE TITLE
Error when saving notebooks in write-protected directory

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-notebook#150]
@JiangShenLi-1703 commented on [Mon May 28 2018](https://github.com/spyder-ide/spyder/issues/7216)

 

### What steps will reproduce the problem?

Using the spyder-notebook plugin, had run a code cell. Then I used righ-mouse-button on the 'untitled' tab, to save and rename. After hitting ok on the Save, this error popup occured.

### Traceback
```python-traceback
  File "/Users/leejohnson/anaconda3/lib/python3.6/site-packages/spyder_notebook/notebookplugin.py", line 402, in save_as
    nb_contents = nbformat.read(original_path, as_version=4)
  File "/Users/leejohnson/anaconda3/lib/python3.6/site-packages/nbformat/__init__.py", line 138, in read
    with io.open(fp, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/t1/vlw6f83159q7r73w2vg7syxw0000gn/T/spyder-leejohnson/notebooks/untitled1.ipynb'
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.3
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Darwin 17.5.0

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.4.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
```

---

@ccordoba12 commented on [Mon May 28 2018](https://github.com/spyder-ide/spyder/issues/7216#issuecomment-392573780)

Thanks for reporting. I'll move this to the right repo.

**Comment by JiangShenLi-1703** [comment]
I found the directory after restarting from scratch. I was able to save
from a Safari Jupyter notebook. I'll try again from Spyder in a bit. (I
restarted the computer, so the exact path under '/var/...' may be different.

Back in a few...

**Comment by JiangShenLi-1703** [comment]
After the restart, I was able to use the untitled notebook tab under Spyder
to save text I'd edited into a new notebook.
So seems as if the cause can be attributed to the running Anaconda-Jupyter
server in the previous session before I restarted.

On Mon, May 28, 2018 at 12:28 PM, JiangShen Li <youjianbauhuqi2005@gmail.com

**Comment by ccordoba12** [comment]
Ok, thanks for the input. It'll help us to debug this problem in the future.

**Comment by jitseniesen** [comment]
We can at least give a nicer error message.

**Comment by jitseniesen** [comment]
I think I can reproduce the issue, but I am not completely certain it is the same issue. When I tried to use "Save as" to save the notebook in a write-protected directory it, the following error is raised:
```
Traceback (most recent call last):
  File "/home/jitse/misc/spyder-notebook/spyder_notebook/notebookplugin.py", line 416, in save_as
    nbformat.write(nb_contents, filename)
  File "/home/jitse/misc/miniconda/envs/spydernb/lib/python3.6/site-packages/nbformat/__init__.py", line 162, in write
    with io.open(fp, 'w', encoding='utf-8') as f:
PermissionError: [Errno 13] Permission denied: '/jitse4.ipynb'
```
We need to catch this.
