### ISSUE TITLE
Notebook header shows

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-notebook#154]
I think the header of the notebook is supposed to be hidden, but it shows. Need to investigate further.

**Comment by ccordoba12** [comment]
Yes, it should be hidden. We are trying to do that using JS, so probably the notebook JS call to do that changed in one of its last releases.

**Comment by jitseniesen** [comment]
I think I misunderstood what the "header" is. It is the region above the menu bar, isn't it? I originally thought the menu bar was also supposed to be hidden, but I realize now that that might be wrong.

**Comment by ccordoba12** [comment]
> It is the region above the menu bar, isn't it?

Yes, that's right.

> I originally thought the menu bar was also supposed to be hidden

It contain some important actions, so I think we shouldn't hide it. However, we definitely need to override some of those actions that don't make sense for spyder-notebook.

**Comment by jitseniesen** [comment]
Thanks, then the plugin is working as it should. There is already another issue about hiding some of the File menu.
