### ISSUE TITLE
Error when saving notebooks

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-notebook#162]
@manzo1991 commented on [Mon Aug 27 2018](https://github.com/spyder-ide/spyder/issues/7773)

### What steps will reproduce the problem?

save the notebook via Save as... function (top right of the notebook interface)

---

@jitseniesen commented on [Mon Aug 27 2018](https://github.com/spyder-ide/spyder/issues/7773#issuecomment-416167435)

This works for me. I am afraid we need more information in order to solve this issue: what is the error message? What versions? Does this happen all the time when using Save as ...?

---

@ccordoba12 commented on [Mon Aug 27 2018](https://github.com/spyder-ide/spyder/issues/7773#issuecomment-416218600)

Moving to the right repo.

**Comment by ccordoba12** [comment]
Possibly related to #150.

**Comment by jitseniesen** [comment]
Closing because there is not enough information.
