### ISSUE TITLE
Small font size on high resolution screen

### ISSUE THREAD

**Issue by Flancis** [spyder-ide/spyder-notebook#174]
## Description of your problem

On high resolution screen, the font size of the notebook opened within Spyder is too small compared with other areas of the Spyder interface, as shown in the following figure.
<img width="894" alt="resolution" src="https://user-images.githubusercontent.com/26384469/46692039-80f1cb00-cc06-11e8-8438-868ad5909d14.png">

**What steps will reproduce the problem?**

1. Just open the spyder notebook on a high resolution computer.

**What is the expected output? What do you see instead?**
It is expected that the font in the notebook area is the same as other areas. However, it is much smaller.

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**

## Versions and main components

* Spyder Version: 3.3.1
* Python Version: 3.6.6
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Jupyter Notebook Version: 5.7.0
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Thanks for the report. We'll take a look at this in a future release.

**Comment by lwbaqueros** [comment]
Is there any way I can increase the font size of a Jupiter notebooks in Spyder-Notebook?

**Comment by mmagnuski** [comment]
@lwbaqueros You can right-click somewhere in the notebook and choose "zoom in" - this will scale up the notebook elements. Unfortunatelly, you will often have to perform this action multiple times to get desired scaling and you have to do it for each notebook separately. It would be nice to have some setting of default notebook scale.

**Comment by lwbaqueros** [comment]
@mmagnuski Thanks for the clarification. I was too used to the `Ctrl+Scroll` that I did not notice the right click.

**Comment by cliffckerr** [comment]
+1 on this issue -- having to go through this process >10 times just to get the font size the same as the main editor is a bit annoying. (Awesome plugin though, just discovered it!!)

**Comment by Karlheinzniebuhr** [comment]
Having the same problem, have to zoom in every time I open a notebook, pretty annoying :(

**Comment by Zalnd** [comment]
> @lwbaqueros **You can right-click somewhere in the notebook and choose "zoom in" - this will scale up the notebook elements.** Unfortunatelly, you will often have to perform this action multiple times to get desired scaling and **you have to do it for each notebook separately**. It would be nice to have some setting of default notebook scale.

The 'welcome notebook template' should include this info.

**Comment by jitseniesen** [comment]
> The 'welcome notebook template' should include this info.

Done in PR #409
