### ISSUE TITLE
maybe a bug?

### ISSUE THREAD

**Issue by adaaaaaa** [spyder-ide/spyder-notebook#176]
just find some spyder-notebook's strange [perform](https://github.com/dunovank/jupyter-themes/issues/291)
at first i think it's jupyter-themes' problem,but when i reset it to default,the same thing happen again and again...
how to fix it?

**Comment by adaaaaaa** [comment]
maybe you could try this?
[backprop.zip](https://github.com/spyder-ide/spyder-notebook/files/2477025/backprop.zip)

zoom in about 3 or 4times the bug will reproduce...

**Comment by Flancis** [comment]
@adaaaaaa The issue did not reproduce here.

**Comment by adaaaaaa** [comment]
@Flancis what may cause it and what should i do?

**Comment by jitseniesen** [comment]
This is all about version 0.1 of the plugin, we never managed to reproduce it and we have just released version 0.3, so I am closing this issue. If anybody encounters the same problem with version 0.3, please open a new issue so that we can get to the bottom of it.
