### ISSUE TITLE
opening links from spyder-notebook opens the notebook in browser asking for token

### ISSUE THREAD

**Issue by mmagnuski** [spyder-ide/spyder-notebook#185]
## Description of your problem

**What steps will reproduce the problem?**

1. Open a notebook with a link in a markdown cell.
2. Click the link

**What is the expected output? What do you see instead?**
expected: opens desired link in the browser
actual: the browser shows the page that asks for notebook token (which is harder to find if notebook was run from Spyder). When provided with the token, the notebook is opened in this browser tab (but not the desired link).

## Versions and main components
```
# Name                    Version                   Build  Channel
spyder                    3.3.1                    py36_1
spyder-kernels            0.2.6                    py36_0
spyder-notebook           0.1.3                    py36_0    spyder-ide
python                    3.6.6                hea74fb7_0
pyqt                      5.9.2            py36h6538335_2
qt                        5.9.6            vc14h1e9a669_2  [vc14]
jupyter                   1.0.0                    py36_7
jupyter_client            5.2.3                    py36_0
jupyter_console           6.0.0                    py36_0
jupyter_core              4.4.0                    py36_0
jupyterlab                0.35.1                   py36_0
jupyterlab_launcher       0.13.1                   py36_0
jupyterlab_server         0.2.0                    py36_0
```
* Operating system: Windows 10

but I've seen this problem on multiple computers. The workaround is to edit the markdown cell and copy the link of course, but it would be nice if it worked.

**Comment by ccordoba12** [comment]
Thanks for reporting. This is a valid concern and we'll try to address it in the future.

**Comment by aviolov** [comment]
For reference, i get the same issue. This is minor b/c i can just copy-paste the link, but what is worse is that I get the same token-authentication when i try to e.g. File->Download as -> .html

The weird thing is that i somehow got it to work by accident by some combination of restart (downloading via the browser started working) but i can't remember how.

Part of the problem may be that the token is not being handed correctly to the browser, b/c if I just do 
`jupyter notebbok list` in a prompt i can see my spyder notebook server running, paste their token into the browser and all is good from there

A related info-bit might be that I seem to have two servers running 

```
http://localhost:8889/?token=2586...
http://localhost:8888/?token=80c7...
````

and i am trying to eport a notebook running on the former one (port:8889),

**Comment by jitseniesen** [comment]
I reproduced this with version 0.3.0 of the plugin. Clicking on a link in the notebook opens the notebook in my browser, not the link (though it does not ask for a token in my case).

The "Download as HTML" option has gone, so that part of the issue has disappeared.

**Comment by mmagnuski** [comment]
Yes, the `0.3.0` does not ask for the token - that's already an improvement!
