### ISSUE TITLE
Got this after installation: [isort] Sorry, can't use kernel language python3. Configurations are currently only defined for the following languages: python 

### ISSUE THREAD

**Issue by bat67** [spyder-ide/spyder-notebook#188]
I found this plugin today, and I think it's great! But when I installed it using `conda install spyder-notebook -c spyder-ide`, as the [Installation](https://github.com/spyder-ide/spyder-notebook#installation) says, nothing happened after I restarted my Spyder. I can't find `View-->Panes-->Notebook`. Then I uninstalled it and installed manually following the [User plugins Wiki](https://github.com/spyder-ide/spyder/wiki/User-plugins#install) and this issue #140 . This time `Notebook` option is there, but I got this every time when Spyder starts: `[isort] Sorry, can't use kernel language python3. Configurations are currently only defined for the following languages: python. See Readme for details`. Also, this plugin isn't worked well.
<img width="492" alt="error" src="https://user-images.githubusercontent.com/16974546/50142694-aa556400-02e5-11e9-86ac-f9e0e5f577d7.png">
So my questions are, why is conda installation not working and why did I get this error after manually installation?

Here are some version informations:
Spyder: 3.3.2
Python: 3.6
Qt: 5.9.5
Pyqt: 5.9.2
Notebook: 5.6.0
OS: Windows 10

Dependencies:
IPython >=4.0     :  6.4.0 (OK)
cython >=0.21     :  0.28.2 (OK)
jedi >=0.9.0      :  0.12.0 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.14.3 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.8.4 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.7.4 (OK)
sympy >=0.7.3     :  1.1.1 (OK)

Thanks in advance!❤

**Comment by ccordoba12** [comment]
I have no idea what the error you're getting means, sorry.

**Comment by bat67** [comment]
After so many times unsuccessful attempts, I stumbled across the reason of this weird issue. 

The error occurred because of the [isort formatter jupyter nbextension](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/code_prettify/README_isort.html) I had enabled, which is one of the extensions in [jupyter-contrib-nbextensions](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/#). When I disabled it, everything works fine. I also tried other extensions I often use, some works well (such as Tables of Contents, Split Cells Notebook, Split Cells Notebook etc.), some don't work without errors (such as Variable Inspector etc.), and some don't work but will give an error (such as isort formatter I mentioned upon).

I don't know why this jupyter nbextension don't have a good compatibility with the spyder-notebook, which works fine after I disabled the nbextension.  😃 

So now issue solved, please close this issue. Thanks!

**Comment by rn2208** [comment]
I had the same thing only with the autopep8 module. In the settings of the module itself, you could change "python" to "python 3".

**Comment by QinyangHe** [comment]
Thank you a lot. I met the same problem when trying to use Julia. You helped me solve it!

**Comment by aweng126** [comment]
I met the similar problem the description of which is following
> [autopep8] Sorry, can't use kernel language octave. Configurations are currently only defined for the following languages: python. See Readme for details.

definitely this problem was releted with the autopep8. so i open the Nbextensions panel and then  disable the autopep8 extensions. 
![]( https://cdn.kingwen.cn/qiniu_kwimg20201016113535.png)
then the problem solved.

**Comment by jarrelldunson** [comment]
08-06-2022 - I got this, after installing the R-kernel:

localhost:8889 says 
[autopep8] Sorry, can't use kernel language r

The autopep8 is a Jupyer NB Extension that I has enabled. Once I disabled it, then my R-Kernel would run.
