### ISSUE TITLE
Hi, how to create a jupyter notebook in spyder?  

### ISSUE THREAD

**Issue by wangzhichao1990** [spyder-ide/spyder-notebook#189]
I can't find the "+" symbol to create a notebook after I install the spyder-notebook plugin with pip .
The below is the version of softwares. 
Python 3.6.7
spyder                   3.3.2      
spyder-kernels           0.3.0      
spyder-notebook          0.1.3      
spyder-terminal          0.2.4
AnyQt                    0.0.10     
PyQt5                    5.9.2      
QtAwesome                0.5.3      
QtPy                     1.5.2
pyqtgraph                0.10.0     
qtconsole                4.4.3  
OS ubuntu 18.04LTS

**Comment by mmagnuski** [comment]
You need to provide some more information also on what you do see not only what you don't. Do you see the notebook tab? If not, go to view -> panes and allow notebook pane there.

**Comment by ccordoba12** [comment]
This happens because Spyder 3.3.2 is incompatible with the spyder-notebook 0.1.3. It's going to be fixed in the next release.

**Comment by ccordoba12** [comment]
The next release of spyder-notebook, I meant.
