### ISSUE TITLE
Moving open notebook generates an error

### ISSUE THREAD

**Issue by jiggensnaggen** [spyder-ide/spyder-notebook#194]
### What steps will reproduce the problem?

i moved a file that was open to another location. 

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_notebook\notebookplugin.py", line 374, in close_client
    nb_contents = nbformat.read(path, as_version=4)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbformat\__init__.py", line 138, in read
    with io.open(fp, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\s516583\\AppData\\Local\\Temp\\spyder\\notebooks\\untitled2.ipynb'
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 3.3.2 
* Python version: 3.7.1
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. Your bug is valid because we haven't considered what you did.

However, `spyder-notebook` is unmaintained until we release Spyder 4, sorry. For now, please avoid doing what you reported.

**Comment by gersonjferreira** [comment]
Great that this is reported as well. I just want to add, if relevant, that it also happens when I use the 'recent files' list and open a file that doesn't exist anymore, or that was moved somewhere else. Basically, it fails whenever we try to close a tab from a file that doesn't exist anymore. 

I understand we have to wait for Spyder 4.

**Comment by jitseniesen** [comment]
This is the same issue as #187 so I am closing it as a duplicate.
