### ISSUE TITLE
Can i embed spyder-notebook or console in my own  python software?

### ISSUE THREAD

**Issue by JerSefJeTu** [spyder-ide/spyder-notebook#199]
## I want to embed spyder-notbook or sypder-terminal in  my own python software.

So my question is can i integrate notebook or terminal in my software as widgets? My complete software is written in PyQt5 . it would be nice and useful if I could use you terminal or notebook. But I do not know that something is so possible.

Cheers.

**Comment by ccordoba12** [comment]
> So my question is can i integrate notebook or terminal in my software as widgets?

I don't think so. After the changes I'm preparing in PR #198, it won't be possible to use this plugin without Spyder. And similar changes will come for spyder-terminal too.

**Comment by JerSefJeTu** [comment]
Is there anyway the possibility of embedding components from spyder into my software, because in the project description it says that it works through plugins?
