### ISSUE TITLE
Set Default Root Directory of Spyder-notebook

### ISSUE THREAD

**Issue by BriFuture** [spyder-ide/spyder-notebook#201]
## Description of your problem

**What steps will reproduce the problem?**

1.  Open Spyder, spyder-notebook will automately luanched
2.  visit localhost:8888, the directory showed in browser seems to be `%USER_PROFILE%`

**What is the expected output? What do you see instead?**
How to set the default directory of spyder-notebook. For example, if I launch jupyter-notebook.exe under `G:/`, the root directory of notebook is `G:/`. I'd like to have spyder-notebook work the same way

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**
![image](https://user-images.githubusercontent.com/7582298/56173788-c82b9f00-6021-11e9-9e82-e59db45e2c5e.png)

## Versions and main components

* Spyder Version:  3.3.3
* Python Version: 3.6.5
* Qt Version: 5.12.0
* PyQt Version: 5.12.0
* Jupyter Notebook Version:   5.7.6
* Operating system: Windows 10 x86-64

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=4.0     :  7.2.0 (OK)
cython >=0.21     :  None (NOK)
jedi >=0.9.0      :  0.13.2 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
numpy >=1.7       :  1.16.2 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.2.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  1.8.3 (OK)
sympy >=0.7.3     :  None (NOK)

**Comment by ccordoba12** [comment]
There's no need for that because you can simply use the Open dialog we provide to open a new notebook anywhere you want.

Please see the video in our Readme:

https://github.com/spyder-ide/spyder-notebook/blob/master/README.md

to understand how to use our plugin.
