### ISSUE TITLE
Why spyder does not response ?  

### ISSUE THREAD

**Issue by Osman-Rafi** [spyder-ide/spyder-notebook#202]
## Description of your problem

**What steps will reproduce the problem?**

1. When i am trying to run code the variable explorer and ipython console is not showing expected output
2. **ipython shell is showing** runfile('C:/Users/Osman Rafi/Desktop/untitled1.py', wdir='C:/Users/Osman Rafi/Desktop')
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**

## Versions and main components

* Spyder Version: 3.3.3
* Python Version:3.7
* Qt Version:
* PyQt Version:
* Jupyter Notebook Version:
![Annotation 2019-04-22 160919](https://user-images.githubusercontent.com/33856265/56496007-90d55a80-6519-11e9-89f2-946bf0c8c2db.png)

* Operating system: Win 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Please post your problem here:

https://gitter.im/spyder-ide/public

to get help.
