### ISSUE TITLE
Problem on Windows 10 using jupyter notebooks

### ISSUE THREAD

**Issue by gabrielraya** [spyder-ide/spyder-notebook#205]
I am not able to use the jupyter notebooks, you can see the problem I have in the next image:
![error](https://user-images.githubusercontent.com/15808937/57983453-5ac0c300-7a52-11e9-8786-6123ff560c58.PNG)

I did the following:
1.  install it with "conda install spyder-notebook -c spyder-ide", and my OS is windows 10 Education

## Versions and main components
 
* Spyder Version: 3.3.4 
* Python Version: 3.6 
* Operating system: Windows 10 Education.

I modified the python interpreter path to use my new environment directly from spyder, on `Preferences> Python Intrepreter` > `Use the following Python interpreter`

## Dependencies
absl-py==0.7.1
alabaster==0.7.12
asn1crypto==0.24.0
astor==0.7.1
astroid==2.2.5
attrs==19.1.0
Babel==2.6.0
backcall==0.1.0
bleach==3.1.0
certifi==2019.3.9
cffi==1.12.3
chardet==3.0.4
cloudpickle==1.0.0
colorama==0.4.1
coloredlogs==10.0
cryptography==2.6.1
cycler==0.10.0
decorator==4.4.0
defusedxml==0.6.0
docutils==0.14
entrypoints==0.3
gast==0.2.2
grpcio==1.20.1
h5py==2.9.0
humanfriendly==4.18
idna==2.8
imageio==2.5.0
imagesize==1.1.0
ipykernel==5.1.0
ipython==7.5.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
isort==4.3.19
jedi==0.13.3
Jinja2==2.10.1
joblib==0.13.2
jsonschema==3.0.1
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-core==4.4.0
Keras==2.2.4
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.9
keyring==18.0.0
kiwisolver==1.1.0
lazy-object-proxy==1.4.1
Mako==1.0.7
Markdown==3.1
MarkupSafe==1.1.1
matplotlib==3.1.0
mccabe==0.6.1
mistune==0.8.4
mkl-fft==1.0.12
mkl-random==1.0.2
mock==3.0.5
nbconvert==5.5.0
nbformat==4.4.0
networkx==2.3
notebook==5.7.8
numpy==1.16.3
numpydoc==0.9.1
packaging==19.0
pandas==0.24.2
pandocfilters==1.4.2
parso==0.4.0
pickleshare==0.7.5
Pillow==6.0.0
prometheus-client==0.6.0
prompt-toolkit==2.0.9
protobuf==3.7.1
psutil==5.6.2
pycodestyle==2.5.0
pycparser==2.19
pyflakes==2.1.1
Pygments==2.4.0
pygpu==0.7.6
pylint==2.3.1
pyOpenSSL==19.0.0
pyparsing==2.4.0
pyreadline==2.1
pyrsistent==0.14.11
PySocks==1.7.0
python-dateutil==2.8.0
pytz==2019.1
PyWavelets==1.0.3
pywin32==223
pywinpty==0.5.5
PyYAML==5.1
pyzmq==18.0.0
QtAwesome==0.5.7
qtconsole==4.4.4
QtPy==1.7.1
requests==2.22.0
rope==0.14.0
scikit-image==0.15.0
scikit-learn==0.21.1
scipy==1.2.1
Send2Trash==1.5.0
SimpleITK==1.2.0
six==1.12.0
sklearn==0.0
snowballstemmer==1.2.1
Sphinx==2.0.1
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
spyder==3.3.4
spyder-kernels==0.4.4
spyder-notebook==0.1.4
spyder-terminal==0.2.4
tensorboard==1.13.1
tensorflow==1.13.1
tensorflow-estimator==1.13.0
termcolor==1.1.0
terminado==0.8.2
testpath==0.4.2
Theano==1.0.4
tornado==6.0.2
tqdm==4.32.1
traitlets==4.3.2
typed-ast==1.3.4
urllib3==1.25.2
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.15.4
widgetsnbextension==3.4.2
win-inet-pton==1.1.0
wincertstore==0.2
wrapt==1.11.1

**Comment by ccordoba12** [comment]
This looks like a problem with your firewall and/or antivirus. Please disable them and try again.

**Comment by gabrielraya** [comment]
Now it works!, but I didn't disable the firewall and/or antivirus, I just re-create my environment!
It seems like some library was messing with the notebook, not sure. 
Anyway, Thanks a lot!.
