### ISSUE TITLE
spyder notebook integration error

### ISSUE THREAD

**Issue by anonymous645** [spyder-ide/spyder-notebook#206]
**What steps will reproduce the problem?**

1.  whenever I try to open notebook . I shows me following error.

Expectation
1. Expected to open notebook in spyder.

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Jupyter Notebook Version:
* Operating system:

Latest version off all above mentioned.

## Dependencies
IPython >=4.0     :  7.4.0 (OK)
cython >=0.21     :  0.29.6 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
numpy >=1.7       :  1.16.2 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.12.0 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
sympy >=0.7.3     :  1.3 (OK)
![Screenshot (106)](https://user-images.githubusercontent.com/49645689/60013392-fec60b80-969b-11e9-991d-f3e113ef8fae.png)

**Comment by ccordoba12** [comment]
This is most probably caused by your firewall/antivirus blocking the Jupyter notebook server (it even mentioned it in the screenshot you uploaded)

If you want more help, please take the time to fill the info we request (instead of simply skipping it):

> Spyder Version:
    Python Version:
    Qt Version:
    PyQt Version:
    Jupyter Notebook Version:
    Operating system:

**Comment by anonymous645** [comment]
I Have updated my issue and mentioned all required details. One thing I think I should bring in your notice is that yesterday when I installed this plugin it asked me to set password for your notebook . so I set my notebook  password by command
`jupyter notebook --generate-config
$ jupyter notebook password
Enter password:  ****
Verify password: ****`
[NotebookPasswordApp] Wrote hashed password to /Users/you/.jupyter/jupyter_notebook_config.json"

As mentioned in documentation  here 
[https://jupyter-notebook.readthedocs.io/en/stable/public_server.html](url)

possibly it merged due to this thing. any other help would be appreciated.

**Comment by ccordoba12** [comment]
>  One thing I think I should bring in your notice is that yesterday when I installed this plugin it asked me to set password for your notebook

I doubt that's the problem.

----

Please deactivate your firewall/antivirus and try again. That should fix your problem.

**Comment by anonymous645** [comment]
Turned  firewall off still of no use. Still not working . even  when I open it , it crashes my whole spider
![Screenshot (107)](https://user-images.githubusercontent.com/49645689/60017984-b01e6e80-96a7-11e9-82ed-9fd3d3ec0eb3.png)


![Screenshot (108)](https://user-images.githubusercontent.com/49645689/60017868-72b9e100-96a7-11e9-8519-a1a1336fda9a.png)

**Comment by anonymous645** [comment]
I think  I should uninstall it and try to install it again. Can you tell me how to install this extension.

**Comment by ccordoba12** [comment]
> Still not working . even when I open it , it crashes my whole spider

Please use the dialog that appears in your screenshot (the one that starts with `Spyder has encountered an internal problem`) to post your problem directly to Github. That dialog contains the information necessary for us to better help you.
