### ISSUE TITLE
spyder 4.0 and spyder noteboo 0.1.4

### ISSUE THREAD

**Issue by arita37** [spyder-ide/spyder-notebook#210]
## Description of your problem

**What steps will reproduce the problem?**

1.  conda create -n py36 python=3.6.5
2.  conda install spyder-notebook -c spyder-ide

**What is the expected output? What do you see instead?**

Cannot notebook tabs....

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**

## Versions and main components

* Spyder Version:
* Python Version:  3.6.5
* Qt Version:  
* PyQt Version:
* Jupyter Notebook Version:
* Operating system:
Windows 7.0

## Dependencies
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
pyls >=0.27.0     :  0.27.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  None (NOK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.5.0 :  4.5.1 (OK)
IPython >=4.0     :  7.6.1 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.3.1 (OK)

# packages in environment at C:\D\anaconda3\envs\py36:                          
#                                                                               
# Name                    Version                   Build  Channel              
alabaster                 0.7.12                   py36_0                       
argh                      0.26.2                py36_1001    spyder-ide         
asn1crypto                0.24.0                   py36_0                       
astroid                   2.2.5                    py36_0                       
atomicwrites              1.3.0                    py36_1                       
attrs                     19.1.0                   py36_1                       
autopep8                  1.4.4                      py_0                       
babel                     2.7.0                      py_0                       
backcall                  0.1.0                    py36_0                       
bleach                    3.1.0                    py36_0                       
ca-certificates           2019.5.15                     0                       
certifi                   2019.6.16                py36_0                       
cffi                      1.12.3           py36h7a1dbc1_0                       
chardet                   3.0.4                    py36_1                       
cloudpickle               1.2.1                      py_0                       
colorama                  0.4.1                    py36_0                       
cryptography              2.7              py36h7a1dbc1_0                       
decorator                 4.4.0                    py36_1                       
defusedxml                0.6.0                      py_0                       
diff-match-patch          20181111                   py_0    spyder-ide         
docutils                  0.14             py36h6012d8f_0                       
entrypoints               0.3                      py36_0                       
future                    0.17.1                   py36_0                       
icu                       58.2                 ha66f8fd_1                       
idna                      2.8                      py36_0                       
imagesize                 1.1.0                    py36_0                       
importlib_metadata        0.17                     py36_1                       
ipykernel                 5.1.1            py36h39e3cac_0                       
ipython                   7.6.1            py36h39e3cac_0                       
ipython_genutils          0.2.0            py36h3c5d0ee_0                       
isort                     4.3.21                   py36_0                       
jedi                      0.13.3                   py36_0                       
jinja2                    2.10.1                   py36_0                       
jpeg                      9b                   hb83a4c4_2                       
jsonschema                3.0.1                    py36_0                       
jupyter_client            5.3.1                      py_0                       
jupyter_core              4.5.0                      py_0                       
keyring                   18.0.0                   py36_0                       
lazy-object-proxy         1.4.1            py36he774522_0                       
libpng                    1.6.37               h2a8f88b_0                       
libsodium                 1.0.16               h9d3ae62_0                       
m2w64-gcc-libgfortran     5.3.0                         6                       
m2w64-gcc-libs            5.3.0                         7                       
m2w64-gcc-libs-core       5.3.0                         7                       
m2w64-gmp                 6.1.0                         2                       
m2w64-libwinpthread-git   5.0.0.4634.697f757               2                    
markupsafe                1.1.1            py36he774522_0                       
mccabe                    0.6.1                    py36_1                       
mistune                   0.8.4            py36he774522_0                       
msys2-conda-epoch         20160418                      1                       
nbconvert                 5.5.0                      py_0                       
nbformat                  4.4.0            py36h3a5bc1b_0                       
notebook                  5.7.8                    py36_0                       
numpydoc                  0.9.1                      py_0                       
openssl                   1.1.1c               he774522_1                       
packaging                 19.0                     py36_0                       
pandoc                    2.2.3.2                       0                       
pandocfilters             1.4.2                    py36_1                       
parso                     0.5.0                      py_0                       
pathtools                 0.1.2                      py_1    spyder-ide         
pexpect                   4.7.0                    py36_0                       
pickleshare               0.7.5                    py36_0                       
pip                       19.1.1                   py36_0                       
pluggy                    0.12.0                     py_0                       
prometheus_client         0.7.1                      py_0                       
prompt_toolkit            2.0.9                    py36_0                       
psutil                    5.6.3            py36he774522_0                       
pycodestyle               2.5.0                    py36_0                       
pycparser                 2.19                     py36_0                       
pydocstyle                3.0.0                    py36_0                       
pyflakes                  2.1.1                    py36_0                       
pygments                  2.4.2                      py_0                       
pylint                    2.3.1                    py36_0                       
pyopenssl                 19.0.0                   py36_0                       
pyparsing                 2.4.0                      py_0                       
pyqt                      5.9.2            py36h6538335_2                       
pyrsistent                0.14.11          py36he774522_0                       
pysocks                   1.7.0                    py36_0                       
python                    3.6.5                h0c2934d_0                       
python-dateutil           2.8.0                    py36_0                       
python-jsonrpc-server     0.1.2                      py_0    spyder-ide         
python-language-server    0.27.0                   py36_0    spyder-ide         
pytz                      2019.1                     py_0                       
pywin32                   223              py36hfa6e2cd_1                       
pywinpty                  0.5.5                 py36_1000                       
pyxdg                     0.26                       py_0    spyder-ide         
pyyaml                    5.1.1            py36he774522_0                       
pyzmq                     18.0.0           py36ha925a31_0                       
qdarkstyle                2.7                        py_0    spyder-ide         
qt                        5.9.7            vc14h73c81de_0                       
qtawesome                 0.5.7                    py36_1                       
qtconsole                 4.5.1                      py_0                       
qtpy                      1.8.0                      py_0                       
requests                  2.22.0                   py36_0                       
rope                      0.14.0                     py_0                       
send2trash                1.5.0                    py36_0                       
setuptools                41.0.1                   py36_0                       
sip                       4.19.8           py36h6538335_0                       
six                       1.12.0                   py36_0                       
snowballstemmer           1.9.0                      py_0                       
sphinx                    2.1.2                      py_0                       
sphinxcontrib-applehelp   1.0.1                      py_0                       
sphinxcontrib-devhelp     1.0.1                      py_0                       
sphinxcontrib-htmlhelp    1.0.2                      py_0                       
sphinxcontrib-jsmath      1.0.1                      py_0                       
sphinxcontrib-qthelp      1.0.2                      py_0                       
sphinxcontrib-serializinghtml 1.1.3                      py_0                   
spyder                    4.0.0b3                  py36_0    spyder-ide         
spyder-kernels            1.4.0                    py36_0    spyder-ide         
spyder-notebook           0.1.4                      py_0    spyder-ide         
sqlite                    3.28.0               he774522_0                       
terminado                 0.8.2                    py36_0                       
testpath                  0.4.2                    py36_0                       
tornado                   6.0.3            py36he774522_0                       
traitlets                 4.3.2            py36h096827d_0                       
typed-ast                 1.3.4            py36he774522_0                       
urllib3                   1.24.2                   py36_0                       
vc                        14.1                 h0510ff6_4                       
vs2015_runtime            14.15.26706          h3a45250_4                       
watchdog                  0.9.0                    py36_1    spyder-ide         
wcwidth                   0.1.7            py36h3d5aa90_0                       
webencodings              0.5.1                    py36_1                       
wheel                     0.33.4                   py36_0                       
win_inet_pton             1.1.0                    py36_0                       
wincertstore              0.2              py36h7fe50ca_0                       
winpty                    0.4.3                         4                       
wrapt                     1.11.2           py36he774522_0                       
yaml                      0.1.7                hc54c509_2                       
yapf                      0.27.0                     py_0                       
zeromq                    4.3.1                h33f27b4_3                       
zipp                      0.5.1                      py_0                       
zlib                      1.2.11               h62dcd97_3

**Comment by arita37** [comment]
ok,

ere

**Comment by ccordoba12** [comment]
We'll fix this after releasing Spyder 4. For now, please stick to Spyder 3 if you want to use this plugin.

**Comment by arita37** [comment]
Spyder notebook is huge huge feature.
It can attract much more users to Spyder

**Comment by arita37** [comment]
When spyder 4 expected to be released ?
Having Jupyter would be a big Plus

**Comment by dbau** [comment]
Hi,

Apparently I am not able to see the notebook tab (spyder 4, rc3). Any news on this issue?

Thanks a lot!
Davide

**Comment by ccordoba12** [comment]
As soon as Spyder 4 is released, we'll also release a new version of sypyder-notebook, compatible with the first one.

**Comment by bsteubing** [comment]
That would be great - I just reverted back to Spyder 3 because of that...

**Comment by jitseniesen** [comment]
The new version of spyder-notebook, compatible with Spyder 4, was released a while ago
