### ISSUE TITLE
spyder-notebook does not show out[#] output

### ISSUE THREAD

**Issue by dosconcombres** [spyder-ide/spyder-notebook#216]
## Description of your problem

**What steps will reproduce the problem?**

1. Installed spyder via anaconda
2. Run any statement.

**What is the expected output? What do you see instead?**
Would expect to see Out[#] and the resulting output. No errors. 

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**

<img width="1680" alt="this" src="https://user-images.githubusercontent.com/2042927/64585955-3efc7680-d3cd-11e9-9b9e-29c7713910bf.png">

## Versions and main components

* Spyder Version: 3.3.6
* Python Version:  3.7.4 
* Qt Version:  5.9.7
* PyQt Version: 5.9.2
* Jupyter Notebook Version: 7.8.0
* Operating system: Mac OS 10.14.6

## Dependencies

IPython >=4.0     :  7.8.0 (OK)
cython >=0.21     :  0.29.13 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
numpy >=1.7       :  1.16.4 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
psutil >=0.3      :  5.6.3 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.5.4 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
sympy >=0.7.3     :  1.4 (OK)
Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
You're not printing anything in your file, that's why you don't any result in our console.

If you want to see the contents for your dataframe, please change your last line from

    df

to

    print(df)

**Comment by dosconcombres** [comment]
Thanks for your response. Okay maybe, but why doesn't notebook display `Out [5]` or something?

**Comment by nh111** [comment]
Hi,

Same Issue I am facing. It is not printing any output in console. please resolve.
