### ISSUE TITLE
Spyder Does Not Display Out [#]

### ISSUE THREAD

**Issue by dosconcombres** [spyder-ide/spyder-notebook#217]
Screen shot attached demonstrates updated Print(df) and not showing the OUT. In screenshots of other systems it clearly shows out, and in those case I don't think "print" would be required to show the dataframe. Please advise.

<img width="1569" alt="thiss" src="https://user-images.githubusercontent.com/2042927/64622745-675e9200-d41a-11e9-9baa-e991cbc77378.png">

_Originally posted by @dosconcombres in https://github.com/spyder-ide/spyder-notebook/issues/216#issuecomment-529960287_

**Comment by ccordoba12** [comment]
`Out[#]` are only generated when you evaluate code directly in the console, not from the Editor.
