### ISSUE TITLE
Trying to save Jupyter notebook crashes notebook plugin, kernel shutdown

### ISSUE THREAD

**Issue by laurajanem** [spyder-ide/spyder-notebook#225]
### What steps will reproduce the problem?

In a new notebook tab, click the arrow menu (upper right of the pane)
Select Save As
Select a save location in the dialog box that opens
Click save
Notebook crashes. 

Console logs from the session:

[I 15:48:07.639 NotebookApp] JupyterLab extension loaded from /Users/lauramariano/opt/anaconda3/lib/python3.7/site-packages/jupyterlab
[I 15:48:07.639 NotebookApp] JupyterLab application directory is /Users/lauramariano/opt/anaconda3/share/jupyter/lab
[I 15:48:07.641 NotebookApp] Serving notebooks from local directory: /var/folders/k4/y7xt4wz91wv2x7zqm6lsgvmh0000gn/T/spyder-lauramariano/notebooks
[I 15:48:07.641 NotebookApp] The Jupyter Notebook is running at:
[I 15:48:07.641 NotebookApp] http://localhost:8888/?token=20cfe92f9e2d672d79b28d023880e00bacae1cf80206a8b8
[I 15:48:07.641 NotebookApp]  or http://127.0.0.1:8888/?token=20cfe92f9e2d672d79b28d023880e00bacae1cf80206a8b8
[I 15:48:07.641 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 15:48:13.870 NotebookApp] Notebook untitled0.ipynb is not trusted
[I 15:48:13.954 NotebookApp] Kernel started: ec07c97d-ffe0-4962-91f1-c392d1d9b7c4
[I 15:48:40.868 NotebookApp] Saving file at /untitled0.ipynb
[I 15:48:47.920 NotebookApp] Kernel shutdown: ec07c97d-ffe0-4962-91f1-c392d1d9b7c4
[I 15:48:49.335 NotebookApp] The port 8888 is already in use, trying another port.
[I 15:48:49.362 NotebookApp] JupyterLab extension loaded from /Users/lauramariano/opt/anaconda3/lib/python3.7/site-packages/jupyterlab
[I 15:48:49.362 NotebookApp] JupyterLab application directory is /Users/lauramariano/opt/anaconda3/share/jupyter/lab
[I 15:48:49.364 NotebookApp] Serving notebooks from local directory: /Users/lauramariano
[I 15:48:49.364 NotebookApp] The Jupyter Notebook is running at:

... kernel restarts

### Traceback
```python-traceback
  File "/Users/lauramariano/opt/anaconda3/lib/python3.7/site-packages/spyder_notebook/notebookplugin.py", line 418, in save_as
    self.create_new_client(filename=filename)
  File "/Users/lauramariano/opt/anaconda3/lib/python3.7/site-packages/spyder_notebook/notebookplugin.py", line 338, in create_new_client
    self.add_to_recent(filename)
  File "/Users/lauramariano/opt/anaconda3/lib/python3.7/site-packages/spyder_notebook/notebookplugin.py", line 256, in add_to_recent
    self.recent_notebooks.insert(0, notebook)
AttributeError: 'str' object has no attribute 'insert'
```

## Versions

* Spyder version: 4.0.0 
* Python version: 3.7.0
* Qt version: 5.13.2
* PyQt5 version: 5.13.2
* Operating System: Darwin 18.7.0

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.3.0 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.5 (OK)
cython >=0.21                :  0.29.14 (OK)
IPython >=4.0                :  7.10.2 (OK)
matplotlib >=2.0.0           :  3.1.2 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
numpy >=1.7                  :  1.17.4 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
applaunchservices >=0.1.7    :  0.2.1 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment]
@jitseniesen, could you take a look at this one?

**Comment by laurajanem** [comment]
Additional piece of possibly helpful info: The file was saved successfully to the directory of choice, it just causes the plugin to crash.

**Comment by jitseniesen** [comment]
> @jitseniesen, could you take a look at this one?

Ok. I may not have time until after Christmas but I will have a look eventually.

**Comment by jitseniesen** [comment]
I just had a quick look and found it is easy to reproduce the issue. Thanks for the report and sorry that our testing did not catch such a major problem.

**Comment by jitseniesen** [comment]
The spyder config file contains a line like
```
recent_notebooks = ['/path/to/file.ipynb']
```
This line is read by `self.get_option('recent_notebooks', default=[])`. where `self` is a `SpyderPluginWidget`. However, this reads the config options as a string, not a list, so the result of `get_option()` is `"['/path/to/file.ipynb']"` in the above example. This causes the error reported.

I think this is a change in what happened in Spyder 3. Any ideas on how to fix? @goanpeca ?

**Comment by jitseniesen** [comment]
Adding
```
    CONF_DEFAULTS = {'recent_notebooks': []}
```
to the notebook plugin seems to do the trick.

I noticed that the file `~/.config/spyder-py3/plugins/notebook/spyder.ini` contains all the Spyder config info and not only the config info of the notebook plugin, as I had expected. Does this indicate that something has gone wrong?

**Comment by ccordoba12** [comment]
> Does this indicate that something has gone wrong?

I think it does and it looks like a bug in the config manager.

@goanpeca, I think we should make the `spyder.ini` file of third-party plugins to be empty if the plugin doesn't declare its `CONF_DEFAULTS`.

**Comment by ccordoba12** [comment]
> I think it does and it looks like a bug in the config manager.

I'm fixing this as part of spyder-ide/spyder#11132. It was a very nasty bug!

**Comment by maciejkos** [comment]
Hi, 

Thank you, folks, for working on Spyder. I have recently moved to Spyder from a popular commercial IDE and love it! 

@jitseniesen -  could you please post how the fixed ```spyder.ini``` should look like? 

I have tried adding ``CONF_DEFAULTS = {'recent_notebooks': []}`` to either the ``[main]`` or the ```[notebook]``` part, but the bug persists. I think I am modifying the correct file because I noticed that Spyder modifies it after opening. For example, it changes this

```
[main]
CONF_DEFAULTS = {'recent_notebooks': []}
recent_notebooks = []
version = 0.0.0
```
to

```
[main]
recent_notebooks = []
conf_defaults = {'recent_notebooks': []}
version = 0.0.0
```

## Versions and main components

* Spyder Version: 4.0.1
* Python Version: 3.7.6 64-bit
* Qt Version: 5.9.7
* PyQt Version: 5.9.2
* Jupyter Notebook Version: 6.0.2
* Operating system: Windows 10


## Dependencies
```atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.11.1 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
zmq >=17                     :  18.1.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
sphinx >=0.6.6               :  2.3.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  None (NOK)
matplotlib >=2.0.0           :  3.1.1 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  None (NOK)
```
Thank you,
-M.

**Comment by idl-paulyee** [comment]
@maciejkos, FYI I had the same issue and I think I tracked it down to this commit (https://github.com/spyder-ide/spyder-notebook/pull/234/commits/94ad1b2caf0fea35b70a133c0fb3fcaf461c1c2f) which I manually edited into ```C:\ProgramData\Miniconda3\pkgs\spyder-notebook-0.2.1-py_0\site-packages\spyder_notebook\notebookplugin.py``` (since I'm using Miniconda on Windows 10), i.e. ,changing line 51 from

```python
CONF_DEFAULTS = {'recent_notebooks': []}
```
to the commit's

```python
CONF_DEFAULTS = [(CONF_SECTION, {'recent_notebooks': []})]
```
After restarting both the Jupyter notebook server and Spyder 4.0.1 (with the patched plugin), both closing and saving notebooks no longer give these errors.  BTW, from the associated PR, it appears that this fix will be coming in the next version 0.2.2 (@jitseniesen can confirm).  Hope this helps,

**Comment by jitseniesen** [comment]
That is correct.

I seem to remember from my testing that closing and saving notebooks works without an error in version 0.2.1 of the spyder-notebook plugin, but according to you that is not the case. That makes it rather more urgent to release another version. Thanks for the feedback.

**Comment by maciejkos** [comment]
@idl-paulyee , @jitseniesen - the patch worked, thanks!

For others with the same issue, in my case, the file to modify was located here:
``C:\Users\Maciej\Anaconda3\pkgs\spyder-notebook-0.2.1-py_0\site-packages\spyder_notebook\notebookplugin.py``
