### ISSUE TITLE
Unable to view variables in variable explorer in 4.0.1 spyder version

### ISSUE THREAD

**Issue by chandrika-gavireddy** [spyder-ide/spyder-notebook#233]
Unable to view variables in variable explorer in 4.0.1 spyder version

![spyder](https://user-images.githubusercontent.com/53118593/72369119-71283700-3725-11ea-8e39-e3628390a41b.jpg)

**Comment by ccordoba12** [comment]
You need to connect a console to the notebook. Please go to the Options menu (the hamburger menu) on the top right corner of the Notebook pane and select the entry called "Open console". Then evaluate something in that console to see the variables declared in the notebook.
