### ISSUE TITLE
Newer Version of Spyder does not launch from Anaconda env but only older one

### ISSUE THREAD

**Issue by PraveenTumma** [spyder-ide/spyder-notebook#237]
## Description of your problem
The newer version of the spyder (4.0.1) does not launch from the Anaconda environment but only the older version, 3.3.2 launches which is available in base anaconda environment.

**What steps will reproduce the problem?**

1. Create a new anaconda envi. and upgrade the Spyder version in it to 4.0.1 from existing 3.3.2 
2. Launch the Anaconda navigator and select the new environment and launch spyder 4.0.1
3. Spyder launches sucessfully but when the version of it is checked in Help->About Spyder, it shows still 3.3.2

**What is the expected output? What do you see instead?**
It should show Spyder 4.0.1 instead 3.3.2

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**

Screenshots attached.
PythonCPU env:
![image](https://user-images.githubusercontent.com/29669079/73978148-aa6a5600-4923-11ea-98c0-8a31929410f3.png)

Base env:

![image](https://user-images.githubusercontent.com/29669079/73978240-db4a8b00-4923-11ea-9189-b66efb46ef91.png)

Spyder version:
![image](https://user-images.githubusercontent.com/29669079/73978291-f1584b80-4923-11ea-9e9c-a71104089396.png)

Launching from Anaconda prompt also same issue:
![image](https://user-images.githubusercontent.com/29669079/73978352-1056dd80-4924-11ea-9cb8-d5443f621d7b.png)

## Versions and main components

Python 3.6.10 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 8.1 

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Please open the Anaconda Prompt and run there these commands

    conda activate PythonCPU
    spyder --reset
    spyder --debug-info verbose

and post here what errors you see in the prompt after running the last command.

**Comment by jitseniesen** [comment]
Closing because no additional information was provided
