### ISSUE TITLE
Move CI to github actions

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder-notebook#241]
## Description of your problem

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**

## Versions and main components

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Jupyter Notebook Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by jitseniesen** [comment]
I am having a go at this.
