### ISSUE TITLE
Cannot undock "Notebook" pane

### ISSUE THREAD

**Issue by ikeszvpvb9ye** [spyder-ide/spyder-notebook#245]
## Spyder 4.0.1 - "Notebook" pane not possible undock

**What steps will reproduce the problem?**
1. Open the newly installed Spyder
2. In the context menu of the pane "Noteboook" do not find the option "Undock"
3. Select the menu item "View - Windows Layout - Spyder Default layout"
4. Observe how the "Notebook" panel automatically dock in group with other panes (variables explorer, plots)
5. Undock all panes from this panes group
6. Observe the lone pane "Notebook" stretched over the entire workspace
7. Still not finding the "Undock" option in the context menu of the pane "Noteboook"
8. Go to reinstall Anaconda

## Versions and main components

* Spyder Version: 4.0.1
* Python Version: 3.7.6
* Qt Version: 5.12.5
* PyQt Version: 5.12.3
* Operating system: Win10 x64 1909
see more [conda list.txt](https://github.com/spyder-ide/spyder-notebook/files/4271849/conda.list.txt)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.13.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.7.0 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  19.0.0 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.7.0 (OK)
qtconsole >=4.6.0            :  4.7.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.4 (OK)
sphinx >=0.6.6               :  2.4.3 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)

**Comment by jitseniesen** [comment]
Thanks for your report. We will try to incorporate this in version 0.3.0.
