### ISSUE TITLE
Spyder 4.0.1 - "Notebook" jupiter kernel does not start automatically

### ISSUE THREAD

**Issue by ikeszvpvb9ye** [spyder-ide/spyder-notebook#246]
## Spyder 4.0.1 - "Notebook" jupiter kernel does not start automatically

**What steps will reproduce the problem?**
1. Open Anaconda Navigator and launch Spyder
2. Go to the "Notebook" pane
3. Open or create a new note
4. Get an error (see screenshot)

**What is the expected output? What do you see instead?**
If there is a spyder-notebook plugin at startup, Spyder automatically checks the integrity and compatibility with the installed version of Jupyter, automatically launches the jupiter kernel

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**
![0001](https://user-images.githubusercontent.com/52958114/75627598-96440c80-5be2-11ea-90b5-1b14240249f1.png)

## Versions and main components

* Spyder Version: 4.0.1
spyder-kernels            1.8.1     
spyder-line-profiler      0.2.0            
spyder-memory-profiler    0.2.0    
spyder-notebook           0.2.2    
spyder-reports            0.1.1      
spyder-terminal           0.2.4 
spyder-unittest           0.4.0  
* Python Version: 3.7.6
* Qt Version: 5.12.5
* PyQt Version: 5.12.3
* Jupyter Notebook Version:
jupyter                   1.0.0   
jupyter_client            6.0.0 
jupyter_console           6.0.0             
jupyter_core              4.6.3 
jupyterlab                2.0.0   
jupyterlab_server         1.0.6 
* Operating system: Win10 x64 1909
see more [conda list.txt](https://github.com/spyder-ide/spyder-notebook/files/4271849/conda.list.txt)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.13.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.7.0 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  19.0.0 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.7.0 (OK)
qtconsole >=4.6.0            :  4.7.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.4 (OK)
sphinx >=0.6.6               :  2.4.3 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)

**Comment by ccordoba12** [comment]
This seems like a firewall issue. Please deactivate it and/or your antivirus too, and try again.

**Comment by ikeszvpvb9ye** [comment]
@ccordoba12 The problem was solved by the firewall settings, some of the bat-files were in the "Weak restrictions" group, therefore the Jupiter kernel did not start automatically

**Comment by ccordoba12** [comment]
Great! Can we close this one then?

**Comment by ikeszvpvb9ye** [comment]
Yes, thanks
