### ISSUE TITLE
Spyder 4.0.1 - "Notebook"  - an attempt to cross a snake and a boa constrictor?

### ISSUE THREAD

**Issue by ikeszvpvb9ye** [spyder-ide/spyder-notebook#247]
## From the cases in the spyder interface after installing spyder-notebook, you feel sick and want to cry

**Suggestions for Improvement**

It’s not at all convenient to use all this now, and there are also a number of problems
https://github.com/spyder-ide/spyder-notebook/issues/115
https://github.com/spyder-ide/spyder-notebook/issues/244
https://github.com/spyder-ide/spyder-notebook/issues/245
https://github.com/spyder-ide/spyder-notebook/issues/246
In the end, I just want to put Inspect Variables in JuputerLab and forget

So the questions are:
1. Does anyone really really need to open for reading and editing the * .ipynb file "as markdown"? what for? "Editor" and "Notebook" panes need to be crossed into one pane, when opening a * .ipynb file you just need to add a tab next to regular scripts
2. The functions of the "Notebook" context menu should then move to the functions of the main toolbar. No need to solve the docking problem
3. Clearly separate the functions of the "Run" menu - now something strange is happening. If the script is one content, if notebook is another.
4. Why are there any cell management options in the Run menu? Notebook already contains everything you need to manage them. Hire a UX designer. I don’t see how you can cross a snake and a boa constrictor in this place

**Comment by jitseniesen** [comment]
The Spyder notebook plugin is a work in progress developed by volunteers in their spare time. In particular, there is no money to hire a UX designer, unless you want to donate it.

In answer to your questions:

1. This is planned; see issue #134 
2. Perhaps, but adding buttons to the main Spyder toolbar needs to be discussed from the view point of Spyder. There is a clear danger that if all plugins add buttons to the main Spyder toolbar, the toolbar becomes too big.
3. Yes, we need to rethink Spyder's Run menu and decide what makes sense for notebooks. I am opening issue #248 to track this.
4. Ditto.

**Comment by ccordoba12** [comment]
Closing because these things are covered in other issues.

**Comment by ccordoba12** [comment]
> Hire a UX designer. I don’t see how you can cross a snake and a boa constrictor in this place

And please avoid comments like this in the future. That kind of comments is not really constructive.
