### ISSUE TITLE
Transition to JupyterLab

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-notebook#261]
The old Jupyter notebook is no longer maintained, so we should try to use JupyterLab instead.

The notebook interface is at https://github.com/jupyterlab/jupyterlab/tree/master/packages/notebook . There is an example demonstrating a stand-alone "notebook" at https://github.com/jupyterlab/jupyterlab/tree/master/examples/notebook .

**Comment by jitseniesen** [comment]
I don't see a way to use the normal JupyterLab server to render an HTML page containing a notebook without all the other widgets like the file browser that JupyterLab normally includes. Having an HTML page with all the widgets seems not very useful within Spyder.

However, the notebook example does give an HTML page with a stand-alone notebook so I will see whether I can use that. The disadvantage is that we will have to work with JavaScript which makes the development and release process more complicated than a pure Python solution. The advantage is that it probably gives us a lot of flexibility to integrate the notebook in Spyder.

**Comment by jitseniesen** [comment]
Potential issue: JupyterLab, and the notebook example in particular, is licensed under 3-clause BSD while Spyder uses MIT. The main difference seems to be the third clause: "Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission."

@ccordoba12 @goanpeca Any idea on how significant this is?

**Comment by goanpeca** [comment]
Since it is a plugin it does not have issues with spyder AFaICT. They should be compatible so I think is fine.

**Comment by ccordoba12** [comment]
Yes, it's fine to use code from JupyterLab.
