### ISSUE TITLE
Cannot run spyder notebook

### ISSUE THREAD

**Issue by Jonas231** [spyder-ide/spyder-notebook#262]
## Description of your problem

1.  Can open Notebook in spyder  but there is no icon to start your plugin
2. I don't know how to run a notebook with your plugin. Please provide a guide how to use spyder-notebook in Spyder 4.1.1
3. I installed spyder notebook-0.2.3 with python 3.7 and spyder 4.1.1 via conda

**What steps will reproduce the problem?**

1.  Create a ipynb notebook and try to run it in spyder 

**What is the expected output? What do you see instead?**
I opened a .ipynb notebook but there is no start buttom (like in your video).

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**
![grafik](https://user-images.githubusercontent.com/38330725/77526792-6e676200-6e8b-11ea-840b-d216392dd194.png)

## Versions and main components

* Spyder Version:  4.1.1
* Python Version: 3.7.4 (64 bit)
* Qt Version:   5.9.6
* PyQt Version:   PyQt5 5.9.2
* Jupyter Notebook Version: 6.0.0 (jupyter console)f
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.2.2 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.8.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.5.0 (OK)
numpydoc >=0.6.0               :  0.9.1 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.6.3 (OK)
pygments >=2.0                 :  2.4.2 (OK)
pylint >=0.25                  :  2.3.1 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.5.7 (OK)
qtconsole >=4.6.0              :  4.7.1 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.1.2 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.0 (OK)

# Optional:
cython >=0.21                  :  0.29.13 (OK)
matplotlib >=2.0.0             :  3.1.2 (OK)
numpy >=1.7                    :  1.16.5 (OK)
pandas >=0.13.1                :  0.25.1 (OK)
scipy >=0.17.0                 :  1.3.1 (OK)
sympy >=0.7.3                  :  1.4 (OK)

# Spyder plugins:
spyder_notebook                :  0.2.3 (OK)

**Comment by jitseniesen** [comment]
You need to switch to the Notebook pane. You can do this with the menu item View > Panes > Notebook (I think in German, it is Ansicht > Bereiche > Notebook); if that option does not exist, then there was an issue with initializing the plugin. Once you have the Notebook pane activated, you can open a notebook from inside the pane.

Opening a notebook using the menu item File > Open or the "Open file" button in the toolbar underneath the menu bar will open the notebook in the editor, like in your picture. This is not very useful. One of the priorities for the next release of the plugin is to change this.

**Comment by jitseniesen** [comment]
I am closing this because it is not clear what needs to be done except for resolving #134.

**Comment by cuixing158** [comment]
![run](https://user-images.githubusercontent.com/22857777/92194645-c3c58780-ee9d-11ea-8df9-66c6e341fd99.jpg)
No results are displayed during the operation. Why?

**Comment by mmagnuski** [comment]
@cuixing158 In your screenshot the kernel is still starting ("kernel starting, please wait"), the notebook should be responsive once the kernel is ready.
