### ISSUE TITLE
Allow to change environment in which notebook is run

### ISSUE THREAD

**Issue by hongyi-zhao** [spyder-ide/spyder-notebook#266]
Hi,

I run spyder from a local git repo with the bootstrap.py.  I set the python interpreter of spyder pointing to my project's virtualenv python, and at the same time, I installed the spyder notebook plugin.  But I notice that the python interpreter used by spyder notebook plugin and spyer ipython console is different. The former is the same of the one used by spyer itself, while the latter belongs to the project's virtualenv.

Is this a designed feature? 

Regards

**Comment by jitseniesen** [comment]
Thanks for opening an issue. This is not a conscious design decision, just what was easiest to implement in the first prototype.

It should be possible to change the python interpreter or environment in which the notebook is run.

**Comment by jitseniesen** [comment]
I tried it out and found that the notebooks do actually use the interpreter set in Spyder's preferences but only after you restart Spyder (let me know if it does not work for you). This is a bit different from the IPython consoles within Spyder, where if you change the interpreter in the preferences and then open a new console, that new console picks up the interpreter without needing to restart Spyder.

Similarly, it would be good if notebooks that are opened after you change the interpreter in Spyder's preferences, would pick up and use the new interpreter.

**Comment by ccordoba12** [comment]
@jitseniesen, this is an interesting use case. Perhaps we should allow users to decide what interpreter they want to use for their notebooks and restart the server in the background when they change it in order to support that.
