### ISSUE TITLE
Move functionality out of NotebookPlugin

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-notebook#275]
The `NotebookPlugin` class integrates the plugin into Spyder. However, it implements more of the functionality, like managing notebook tabs and creating new notebooks. This should go in a different class to get a cleaner design and hopefully easier testing. Perhaps I can make a stand-alone application, which can be helpful during development.

**Comment by goanpeca** [comment]
>The NotebookPlugin class integrates the plugin into Spyder. However, it implements more of the functionality, like managing notebook tabs and creating new notebooks. 

Makes sense

>Perhaps I can make a stand-alone application, which can be helpful during development.

Definitely useful!
