### ISSUE TITLE
Cannot save a picture with ALT+RightClick >> CopyImage or SaveImage

### ISSUE THREAD

**Issue by ignacio1988** [spyder-ide/spyder-notebook#279]
Cannot save a picture with ALT+RightClick >> CopyImage or SaveImage

It's a possible save or copy image (Plot) directly with right click and save image?

Best regards

**Comment by jitseniesen** [comment]
No, this does not seem to be possible at the moment. I did not realize that you can do this in a normal notebook. It is a nice suggestion, I can see how this is useful.

Can you give me some details how this works normally, and I can see what we can do. Why do you need to hold down Alt? Is this a browser feature? Are you using Jupyter Notebook or Jupyter Lab? How did you learn about this? Is it described somewhere?

**Comment by ignacio1988** [comment]
Yes in JupiterLab you can save or copy image with ALT+RightClick.  
Please, see follow issues (JupyterLab): https://github.com/jupyterlab/jupyterlab/issues/3043#event-1272299457

Apparently in jupyter notebook is only Righclick >> Save or Copy Image. 
Regards !

**Comment by jitseniesen** [comment]
Thanks, that is helpful. I will have a look.
