### ISSUE TITLE
Creating new notebook fails

### ISSUE THREAD

**Issue by FlorianGreibich** [spyder-ide/spyder-notebook#281]
When I create a new Jupyter Notebook in Spyder, an error message pops up:

Error Loading Notebook
Unreadable Notebook: C:\Users\...\AppData\Local\Temp\spyder\notebooks\untitled5.ipynb FileNotFoundError(2, 'No such file or directory')

But obviously there is no file yet since I am just creating a new one, so this is kind of strange...

**Comment by jitseniesen** [comment]
Your Spyder version is a few months out of date, so you may as well update, but I don't expect that will help with your problem.

At the moment, I don't have an idea what's going wrong, so I just have to ask some general questions in the hope to narrow it down:
* Does this happen every time you create a new notebook in Spyder?
* Can you post a picture of the error message? You will have to do this on GitHub, files attached to email will not reach me.
* After you get the FileNotFoundError, can you check whether the file exists? Does the folder exist? Can you write to it?
* Can you open an existing notebook in Spyder?
* Can you create a new notebook if you run Jupyter normally in your web browser? Can you create a notebook in the same folder C:\Users...\AppData\Local\Temp\spyder\notebooks?

**Comment by jitseniesen** [comment]
Closing due to lack of reply.
