### ISSUE TITLE
Variable explorer in Spyder not working for Notebook anymore after installing Jupyter Variable Explorer

### ISSUE THREAD

**Issue by szfrancis** [spyder-ide/spyder-notebook#282]
## Description of your problem

**What steps will reproduce the problem?**

Ran the following command:
pip install jupyter_contrib_nbextensions
jupyter contrib nbextension install --user
jupyter nbextension enable varInspector/main

And then after restarting Spyder the variable explorer no longer works for embedded Jupyter notebook anymore. 

**What is the expected output? What do you see instead?**
I expect to see variables showing up but now nothing shows up - the variable explorer panel is blank after closing out all other IPython sessions except for the active Notebook session. 

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**
![image](https://user-images.githubusercontent.com/66144508/83309580-a1a1d680-a1d7-11ea-8ef2-7ce95160a25b.png)

## Versions and main components

* Spyder Version: 4.1.3
* Python Version: 3.8.3
* Qt Version: 5.9.7
* PyQt Version: 5.9.2
* Jupyter Notebook Version: 6.0.3
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.5.2 (OK)
pylint >=0.25                  :  2.5.0 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.6.1 (OK)
qtconsole >=4.6.0              :  4.6.0 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  2.4.0 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.1.2 (OK)
numpy >=1.7                    :  1.14.6 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)

# Spyder plugins:
spyder_notebook                :  0.2.3 (OK)

**Comment by jitseniesen** [comment]
Thanks for the report. Your screenshot shows that it is not just that the variable explorer has no variables in it, but it is completely blank (as you say). I would expect there to be error messages somewhere in this case. Try starting Spyder from the command prompt and look for any errors.

Does the Variable Explorer in Spyder work if you are not using notebooks? Did pip install anything else except jupyter_contrib_nbextensions which may interfere?

The next version of the Spyder notebook plugin will be based on Jupyter Lab which probably sidesteps this issue.

**Comment by szfrancis** [comment]
Hi,

Thanks for your reply. I tried closing Spyder and then restarting it from command prompt. However, there is no error when the program starts up and when I go into the "Notebook" tab and re-test what I did I found the problem still persists. 

The variable explorer function is not affected if I am not in the Notebook tab. It only malfunctions for IPython sessions related to notebook sessions. The three lines of commands are the only three lines that caused the issue - immediately before running them there was no problem and immediately after running them the problem occurred. 

Do you have an estimate of when the next version of spyder-notebook will be released? I am eager to try it out and find out if the problem will go away. 

Thanks

**Comment by jitseniesen** [comment]
I tried to follow the same steps as you, but on my computer Spyder's variable explorer still works after I installed and enabled the Jupyter variable explorer. So I still don't know exactly what is going on.

I noticed that on your screenshot, in the upper right hand corner of the notebook, it says "Python 3". Perhaps this suggests that your notebook is not being run with the kernel from Spyder, because then it would say "Python 3 (Spyder)", and this would also explain why Spyder's variable explorer does not work.

Here are some things you could try:
* If in the notebook in Spyder, you go to the "Kernel" menu and pick "Change kernel", what options do you get?
* Does Spyder's variable explorer work if you create a new notebook in Spyder (right click on your notebook and choose "New notebook")? What kernel does it use?
* Does it help if you shutdown or kill all Jupyter servers? Maybe try restarting the computer and opening Spyder right away?

> Do you have an estimate of when the next version of spyder-notebook will be released? I am eager to try it out and find out if the problem will go away.

In two months. If you feel adventurous, you can try running the development version by following the instructions in https://github.com/spyder-ide/spyder-notebook/blob/master/CONTRIBUTING.md .

**Comment by szfrancis** [comment]
Hi,

Thanks for all your help. I remember as someone else has mentioned on the same issue again, uninstalling and then re-installing anaconda would solve the issue. I tried that, and it works exactly as expected. 

I did try your suggestion, but then no matter what I do with the kernal (switch/restart/etc.) won't work.

**Comment by jitseniesen** [comment]
I am glad you managed to fix it. Re-installing does indeed often help, even though I don't really understand why.

**Comment by azarketa** [comment]
To whom it may concern:

Just for the record. Does jupyter_contrib_nbextensions interfere with the functionality of the variable explorer? I am getting the same blank-explorer issue.

**Comment by ccordoba12** [comment]
Well, if you uninstall them and the variable explorer works for you again, then yes.

**Comment by ccordoba12** [comment]
Hey @erbsl, this will be fixed in our next version of Spyder-notebook, which will be released after Spyder 6 is made available in a few weeks.
