### ISSUE TITLE
Inherit dark or light theme from Spyder

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-notebook#290]
Use the dark theme to render notebooks if Spyder is run with the dark theme, and same for the light theme. 

This is part of #191 but seems easier to implement, and it should have a big visual impact.

**Comment by goanpeca** [comment]
@jitseniesen how is the theming of the notebook handled?

**Comment by jitseniesen** [comment]
@goanpeca I don't know, I did not do anything. I assume at the moment the plugin uses the same configuration as Jupyter Lab. There are some files stored in a `.jupyter` directory that seem to store the configuration. 

At the moment, my hope is to somehow change the location of the directory in which the configuration is stored and write a config file suitable for either dark or light theme to that location before starting the server.

**Comment by jitseniesen** [comment]
Fixed by PR #297 .
