### ISSUE TITLE
Spyder Notebook does not open .ipynb file from different drive

### ISSUE THREAD

**Issue by vribbe** [spyder-ide/spyder-notebook#293]
## Spyder Notebook does not open .ipynb file from different driver

I have a conda environment on drive C: with spyder and spyder-notebook and whenever I try to open a notebook .ipynb file from drive D: on spyder-notebook, it shows "404: Not Found; You are requesting a page that does not exist!" and when I close this tab, there is a spyder Server Error message saying "Spyder could not get a list of sessions from the Jupyter Notebook Server. Message: Forbidden". Both Jupyter Lab and Jupyter Notebook run normally if I open them directly from conda prompt. 

Running on Windows 10.

**What steps will reproduce the problem?**
1. Opening the "Notebook" section in Spyder;
2. Opening .ipynb file from drive D: instead of C:

## Versions and main components
Some conda list packages versions that may be helpful:

_anaconda_depends: version 2020.02 - py37_0
anaconda: version custom - py37_1
anaconda-client: version 1.7.2 - py37_0
anaconda-navigator: version 1.9.12 - py37_0
anaconda-project: version 0.8.4 - py_0
conda-package-handling: version 1.6.1 - py37h62dcd97_0
conda-verify: version 3.4.2 - py_1
ipykernel: version 5.1.4 - py37h39e3cac_0
ipython: version 7.13.0 - py37h5ca1d4c_0
ipython_genutils: version 0.2.0 - py37_0
jupyter: version 1.0.0 - py37_7
jupyter_client: version 6.1.3 - py_0
jupyter_console: version 6.1.0 - py_0
jupyter_core: version 4.6.3 - py37_0
jupyterlab: version 1.2.6 - pyhf63ae98_0
jupyterlab_server: version 1.1.4 - py_0
notebook: version 6.0.3 - py37_0
packaging: version 20.3 - py_0
pip: version 20.0.2 - py37_3
pkginfo: version 1.5.0.1 - py37_0
python: version 3.7.7: version h81c818b_4
python-dateutil: version 2.8.1 - py_0
python-jsonrpc-server: version 0.3.4 - py_0
python-language-server: version 0.31.10 - py37_0
python-libarchive-c: version 2.9 - py_0
spyder: version 4.1.3 - py37_0
spyder-kernels: version 1.9.1 - py37_0
spyder-notebook: version 0.2.3 - pyh9f0ad1d_0 - spyder-ide
spyder-unittest: version 0.4.1 - py_0 - spyder-ide

### Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.5.2 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.4 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.4 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

### Optional:
cython >=0.21                  :  0.29.17 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)

### Spyder plugins:
spyder_notebook                :  0.2.3 (OK)
spyder_unittest                :  0.4.1 (OK)

**Comment by jitseniesen** [comment]
Thanks for the report. I cannot try it out right away because I don't have a Windows computer at hand but I will have a look later.

**Comment by hafez-ahmad** [comment]
the code execution cannot proceed because vcruntime140_1.dll was not found

**Comment by jitseniesen** [comment]
I tried to reproduce the original issue, but even with similar versions I can still open notebooks from different Windows drives on my computer. The next version of the plugin, due out by the end of the month, will have better error reporting so hopefully that will help us get to the bottom of this.

**Comment by jitseniesen** [comment]
I am merging this with issue #212 which has very similar reports. As I said, I am hoping that the new release allows us to find out what is going on.
