### ISSUE TITLE
issue "spyder could not get a list of sessions from the jupyter notebook server"

### ISSUE THREAD

**Issue by aurel-lef** [spyder-ide/spyder-notebook#294]
Hello,
Just installed spyder-notebook.
When I opened a notebook the first time, I got the authentification request page and entered the token + set up a password.
But now I got this issue when I tried opening a notebook: "spyder could not get a list of sessions from the jupyter notebook server: Message: forbidden" + 404 http error
Seems to be an authentification issue but I would appreciate some guidelines.
Tried to uninstall and reinstall but the issue remains.
Thanks a lot for your help on this.

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**
screenshot of the issue
<img width="477" alt="Capture" src="https://user-images.githubusercontent.com/66905390/84892393-cd5d0180-b09d-11ea-8070-302aa5a9a753.PNG">

## Versions and main components

* Spyder Version: spyder==4.1.3, spyder-kernels==1.9.1, spyder-notebook==0.2.3
* Python Version: Python 3.7.6
* PyQt Version: QtPy==1.9.0
* Jupyter Notebook Version: jupyter-notebook : 6.0.3
* Operating system: windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.0.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.4 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.4 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)

# Spyder plugins:
spyder_notebook                :  0.2.3 (OK)

**Comment by jitseniesen** [comment]
> When I opened a notebook the first time, I got the authentification request page and entered the token + set up a password.

This is not standard so I want to find out why this happens. 

Did you change something in your installation that you have to set up a password? 

Do you have a notebook configuration file, as described at https://jupyter-notebook.readthedocs.io/en/stable/public_server.html#prerequisite-a-notebook-configuration-file ?

Please go to the Anaconda command prompt and give the command `jupyter notebook list` ; what is the output?

**Comment by aurel-lef** [comment]
Guess what, reboot is the ultimate solution, again... Everything is working now.
Should have done it before writing the issue, sorry, but I do not understand what was wrong.
Regarding your questions:

> Did you change something in your installation that you have to set up a password?
Do you have a notebook configuration file, as described at https://jupyter-notebook.readthedocs.io/en/stable/public_server.html#prerequisite-a-notebook-configuration-file ?

Yes, I set up a configuration file and password after the spyder-notebook install when I realized it was necessary.

> Please go to the Anaconda command prompt and give the command jupyter notebook list ; what is the output?

I have my notebook listed now that it is working, I did not check that when I had the error

Thanks anyway

**Comment by jitseniesen** [comment]
I am glad to see that it resolved itself. I had a similar issue myself once and I wished I had investigated more fully what had happened. Like you, the problem disappeared after a while (probably because I rebooted).
