### ISSUE TITLE
[QUESTION] - How to contribute to this project?

### ISSUE THREAD

**Issue by tienhv** [spyder-ide/spyder-notebook#3]
Hi,

I am also planning to make  this plugin for a long time.  It is nice if there are some persons with the same needs. I want to contribute to this repo, what should I do?

Thanks

**Comment by ccordoba12** [comment]
Thanks for your interest :-)

We'll start to look at this plugin after we release Spyder 3.1 (In mid January). We need to setup first a very basic plugin (to open an embed notebooks in Spyder) and then we'll be glad to accept contributions from the community.

**Comment by ccordoba12** [comment]
There's now PR #4 to provide a very basic implementation of this.
