### ISSUE TITLE
Enable translations

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-notebook#305]
Enable translations and merge translations submitted at Crowdin.

**Comment by ccordoba12** [comment]
When do you plan to release 0.3? Just asking so we can help you with the Spanish translations.

**Comment by jitseniesen** [comment]
I am planning to release 0.3 on 29 July. I told the translators on CrowdIn that have already done some work that all translations up to 28 July will be included.

**Comment by juanis2112** [comment]
@jitseniesen Spanish translations are ready!
