### ISSUE TITLE
is this normal ? (small detail vs normality: using PyQt-5.15)

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder-notebook#309]
## Description of your problem

lauching this script in Spyder-notebook, 
````
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from ipywidgets import interactive
from IPython.display import Audio, display
def beat_freq(f1=220.0, f2=224.0):
    max_time = 3
    rate = 8000
    times = np.linspace(0,max_time,rate*max_time)
    signal = np.sin(2*np.pi*f1*times) + np.sin(2*np.pi*f2*times)
    print(f1, f2, abs(f1-f2))
    display(Audio(data=signal, rate=rate))
    try:
         plt.plot(signal); #plt.plot(v.result);
    except:
         pass
    return signal
v = interactive(beat_freq, f1=(200.0,300.0), f2=(200.0,300.0))
display(v)
````

I would expect this (normal Jupyterlab)
![image](https://user-images.githubusercontent.com/4312421/88948387-2c638800-d292-11ea-890d-a23b67ccd96d.png)

but I don't get the frequency controls in spyder-notebook. Is it normal ?
![image](https://user-images.githubusercontent.com/4312421/88948517-5026ce00-d292-11ea-9630-bea6dba9ef7f.png)

nota: the sound is working ok.

## Versions and main components

* Spyder Version: 4.1.4
* Python Version: 3.8
* Qt Version: 5.15.0
* PyQt Version: 5.15.0
* Jupyter Notebook Version:  2.2.2
* Operating system: Windows 10

## Dependencies

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.0 (OK)
numpy >=1.7                    :  1.19.1 (OK)
pandas >=0.13.1                :  1.1.0 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  1.6.1 (OK)

# Spyder plugins:
spyder_notebook                :  0.3.0 (OK)

**Comment by ccordoba12** [comment]
We don't ship with any JupyterLab extensions, so yes, this is normal.

@jitseniesen, I think we need to create a new package (called perhaps `spyder-jupyterlab`) that ships as much extensions as possible and make Spyder-notebook to depend on it.

**Comment by jitseniesen** [comment]
Yes, getting the more popular extensions to work is quite high on my priority list. I am merging this with the more general #271.
