### ISSUE TITLE
Configure notebook theme seperate from Spyder theme

### ISSUE THREAD

**Issue by jgollub** [spyder-ide/spyder-notebook#310]
I'd like to be able to view a Jupyter notebook with a white background theme and the rest of Spyder with the standard Dark theme. I use Jupyter notebooks for documentation and tutorials and I think it's more readable in a "white paper" format. Whereas for the rest of programming efforts I think the Dark Spyder theme is better for code readability.  Is it possible to have both?

-J

**Comment by jitseniesen** [comment]
This sounds reasonable to me.
