### ISSUE TITLE
Why are other packages downgraded after installation?

### ISSUE THREAD

**Issue by cuixing158** [spyder-ide/spyder-notebook#313]
## Description of your problem
Why are other packages downgraded after installation?
But I still want to use the new version of the library, such as pytorch1.4, torchvision1.5

**What steps will reproduce the problem?**

```conda install spyder-notebook -c spyder-ide```

**What is the expected output? What do you see instead?**
I don’t want to downgrade other library versions, especially pytorch, torchvision

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**
![downgraded](https://user-images.githubusercontent.com/22857777/92102921-d3978a00-ee11-11ea-811a-a5442770ff66.jpg)

## Versions and main components

* Spyder Version: 4.0.0
* Python Version: 3.7
* Qt Version: 
* PyQt Version:
* Jupyter Notebook Version: anaconda1.9.7
* Operating system:win10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by jitseniesen** [comment]
This looks like an issue with the Conda package manager, not Spyder or the plugin, so I am closing this issue. I don't understand why conda wants to downgrade pytorch, but I guess it has to do something with how it handles channels.

Apologies for the delay in handling your issue.
