### ISSUE TITLE
Increase legibility of the notebook dark theme

### ISSUE THREAD

**Issue by mmagnuski** [spyder-ide/spyder-notebook#319]
## Description of the problem

I like the dark theme for the notebook but think that the text and operators color could be a little brighter to increase their visibility (or maybe the background should be different?):

<img src=https://user-images.githubusercontent.com/8452354/94800231-98728180-03e4-11eb-834d-6cbdd3429840.png width="350pix">
<img src=https://user-images.githubusercontent.com/8452354/94800313-b04a0580-03e4-11eb-954f-0c60ac64dbdf.png width="200pix">
<img src=https://user-images.githubusercontent.com/8452354/94800471-e8514880-03e4-11eb-8ee1-2a64eb82ed29.png width="350pix">

## Versions and main components

* Spyder Version:  4.1.5
* Python Version: 3.7.3
* Qt Version: 5.9.7
* PyQt Version: 5.9.2 (pyqt5-sip=12.8.0)
* Operating system: Windows

### jupyter:
```
# Name                    Version                   Build  Channel
jupyter                   1.0.0                    py37_7
jupyter_client            6.1.6                      py_0
jupyter_console           6.2.0                      py_0
jupyter_core              4.6.3                    py37_0
jupyterlab                2.2.6                      py_0
jupyterlab_pygments       0.1.1                      py_0
jupyterlab_server         1.2.0                      py_0
notebook                  6.1.1                    py37_0
spyder-notebook           0.3.0                      py_0    spyder-ide
```

## Dependencies

```
# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.6 (OK)
numpydoc >=0.6.0               :  0.9.1 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.6.3 (OK)
pygments >=2.0                 :  2.7.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.12 (OK)
matplotlib >=2.0.0             :  3.1.0 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  0.25.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)

# Spyder plugins:
spyder_notebook                :  0.3.0 (OK)
```

**Comment by mmagnuski** [comment]
There is also an issue with how matplotlib figures are shown. Often they have transparent background in the default matplotlib inline mode so plotting results in figures like this:
<img src=https://user-images.githubusercontent.com/8452354/94990607-b4f5f180-057d-11eb-87be-fd02b182d597.PNG width="350pix">
while in the light theme they are readable:
<img src=https://user-images.githubusercontent.com/8452354/94990616-bf17f000-057d-11eb-9ff9-979e4153a94e.PNG width="350pix">
This problem does not happen consistently though - sometimes (on some machines?) I correctly get a white background for the plots.

**Comment by jitseniesen** [comment]
You are right, the colours of the quoted text is different in Spyder from when you display the notebook in Jupyter Lab. I agree that this should be fixed.

**Comment by jitseniesen** [comment]
This was changed in Jupyter Lab with PR jupyterlab/jupyterlab#8181 which is part of version 2.1 of Jupyter Lab so the proper fix is to update the versions included in the plugin. However, in the interest of time I will try including a quick but somewhat hacky fix for this particular issue in the next release of the plugin and postpone the proper fix until later.
