### ISSUE TITLE
nothing happens after installation 

### ISSUE THREAD

**Issue by Jacques2101** [spyder-ide/spyder-notebook#328]
<img width="1680" alt="Capture d’écran 2020-10-26 à 14 01 01" src="https://user-images.githubusercontent.com/49912455/97175663-277c7a80-1794-11eb-9523-eeb1e290808d.png">
I installed the notebook extension with conda install spyder-notebook -c spyder-ide as mentioned on the site but nothing happens after launching Spyder. I can't see the notebook (cf. screenshot)

## Versions and main components

* Spyder Version: 4.1.5
* Python Version: 3.8
* Qt Version:5.12.9 
* PyQt Version:5.12.3
* Jupyter Notebook Version:6.1.4
* Operating system: MacOS

## Dependencies

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.3 (OK)
pygments >=2.0                 :  2.7.2 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  None (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)

# Spyder plugins:
spyder_notebook                :  0.3.0 (OK)

**Comment by jitseniesen** [comment]
Try going the Panes submenu of the View menu and selecting Notebook, which should make the notebook pane visible. If that does not help, have a look at the [section "Plugin problems"](https://docs.spyder-ide.org/current/common-illnesses.html#plugin-problems) on the Troubleshooting page of our docs. If that also does not help you to resolve your problem, then please come back here and describe what you tried and found out.

**Comment by Jacques2101** [comment]
it works. Thx

**Comment by Jacques2101** [comment]
Does spyder_notebook works with spyder 5 ? 
I upgraded to version 5.0 and I don't see again notebook even if I follow your previous recommendation 

thx.

**Comment by ccordoba12** [comment]
No, it is not compatible yet.

**Comment by Aryo-Zare** [comment]
> No, it is not compatible yet.

for spyder 5 you can install via conda forge :
`conda install -c conda-forge spyder-notebook`
