### ISSUE TITLE
IPython.display / IFrame does not show a PDF file

### ISSUE THREAD

**Issue by lwbaqueros** [spyder-ide/spyder-notebook#338]
## Description of your problem
I want to confirm it is possible to show the embedded PDF files.
**What steps will reproduce the problem?**
I want to display a PDF file in a frame inside a Jupiter Notebook
1. `from IPython.display import IFrame`
2.` IFrame("my_file.pdf", width=900, height=300)`
3. ![image](https://user-images.githubusercontent.com/46763074/100730676-a5065c80-33ca-11eb-82f2-e85aa8875c0e.png)

**What is the expected output? What do you see instead?**
Normally you have the pdf inside of container
![image](https://user-images.githubusercontent.com/46763074/100730757-c49d8500-33ca-11eb-99f9-c6bf6b6c5175.png)

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**

## Versions and main components

* Spyder Version: 4.1.5
* Python Version: 3.8.5
* Qt Version: 5.9.2
* PyQt Version: 5.9.2
* Jupyter LabVersion:2.2.6
* spyder-notebook: 0.3.1
* Operating system: Ubuntu 20.10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.19.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.2 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.27 (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.1.3 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  None (OK)

# Spyder plugins:
spyder_notebook                :  0.3.1 (OK)
spyder_terminal                :  0.5.0 (OK)

**Comment by jitseniesen** [comment]
Thanks for the report. I can reproduce the issue, but it is not clear to me what is going wrong or how to fix it, so I would welcome a pull request or other help.

**Comment by jitseniesen** [comment]
The [JupyterLab PDF extension](https://github.com/jupyterlab/jupyterlab/tree/master/packages/pdf-extension) may be relevant here, perhaps I can add that extension to Spyder Notebook.
