### ISSUE TITLE
Cannot open console of the spyder-notebook

### ISSUE THREAD

**Issue by unclebob7** [spyder-ide/spyder-notebook#355]
## Description of your problem

**What steps will reproduce the problem?**

1. Spyder 4.1.5
2. jupyter 1.0.0, jupyter_client 6.1.7, jupyter_console 6.2.0

The open-console option appears cannot be selected.

![image](https://user-images.githubusercontent.com/29818505/104991488-d52cbc00-5a59-11eb-9086-d0f216cd5875.png)

**Comment by jitseniesen** [comment]
Sorry that nobody picked this up. Given that this was many years and versions ago, it will probably be impossible to find out what went wrong. If you still see this with a modern version of the plugin, please open a new issue.
