### ISSUE TITLE
The Spyder Notebook server failed to start...

### ISSUE THREAD

**Issue by dkinneyBU** [spyder-ide/spyder-notebook#359]
## Description of your problem
It looks like this has come up a number of times over the years, but seems like it's happening again. When I attempt to open a notebook I get a Server Error popup stating, "The Spyder Notebook server failed to start or it is taking too much time to do it. Please select "Server info" in the plugin's option menu to check for errors." I can open the notebook fine with either jupyter lab or jupyter notebook.

**What steps will reproduce the problem?**

1.  Start Spyder 4.2.1
2. Select the Notebook tab
3. Select Open and select a notebook that has already been partially written in Jupyter Lab.

**What is the expected output? What do you see instead?**
I expect the notebook to open. What I see instead is as above.

## Versions and main components

* Spyder Version: 4.2.1
* Python Version: 3.8.8
* Qt Version: 
* PyQt Version: 1.9.0
* Jupyter Notebook Version: 6.2.0
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.20.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.0.1 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.0 (OK)
pylint >=1.0                    :  2.6.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
setuptools >=39.0.0             :  49.2.1 (OK)
sphinx >=0.6.6                  :  3.5.1 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.1 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  2.0.1 (OK)
zmq >=17                        :  22.0.3 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.19.5 (OK)
pandas >=1.1.1                  :  1.2.2 (OK)
scipy >=0.17.0                  :  1.6.1 (OK)
sympy >=0.7.3                   :  None (NOK)

# Spyder plugins:
spyder_notebook                 :  0.3.2 (OK)
spyder_terminal                 :  0.5.0 (OK)

**Comment by jitseniesen** [comment]
Sorry that nobody picked this up. Given that this was many years and versions ago, it will probably be impossible to find out what went wrong. If you still see this with a modern version of the plugin, please open a new issue.
