### ISSUE TITLE
Support Spyder 5

### ISSUE THREAD

**Issue by bnavigator** [spyder-ide/spyder-notebook#360]
Any plans to support Spyder 5?

```
[   65s] ============================= test session starts ==============================
[   65s] platform linux -- Python 3.8.8, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /usr/bin/python3.8
[   65s] cachedir: .pytest_cache
[   65s] PyQt5 5.15.4 -- Qt runtime 5.15.2 -- Qt compiled 5.15.2
[   65s] rootdir: /home/abuild/rpmbuild/BUILD/spyder-notebook-0.3.2
[   65s] plugins: xvfb-2.0.0, qt-3.3.0, mock-3.1.1, flaky-3.7.0
[   68s] collecting ... collected 21 items / 4 errors / 17 selected
[   68s] 
[   68s] ==================================== ERRORS ====================================
[   68s] ____________ ERROR collecting spyder_notebook/tests/test_config.py _____________
[   68s] ImportError while importing test module '/home/abuild/rpmbuild/BUILD/spyder-notebook-0.3.2/spyder_notebook/tests/test_config.py'.
[   68s] Hint: make sure your test modules/packages have valid Python names.
[   68s] Traceback:
[   68s] /usr/lib64/python3.8/importlib/__init__.py:127: in import_module
[   68s]     return _bootstrap._gcd_import(name[level:], package, level)
[   68s] spyder_notebook/tests/test_config.py:13: in <module>
[   68s]     from spyder.preferences.configdialog import ConfigDialog
[   68s] E   ModuleNotFoundError: No module named 'spyder.preferences.configdialog'
[   68s] ____________ ERROR collecting spyder_notebook/tests/test_plugin.py _____________
[   68s] ImportError while importing test module '/home/abuild/rpmbuild/BUILD/spyder-notebook-0.3.2/spyder_notebook/tests/test_plugin.py'.
[   68s] Hint: make sure your test modules/packages have valid Python names.
[   68s] Traceback:
[   68s] /usr/lib64/python3.8/importlib/__init__.py:127: in import_module
[   68s]     return _bootstrap._gcd_import(name[level:], package, level)
[   68s] spyder_notebook/tests/test_plugin.py:26: in <module>
[   68s]     from spyder_notebook.notebookplugin import NotebookPlugin
[   68s] spyder_notebook/__init__.py:11: in <module>
[   68s]     from spyder_notebook.notebookplugin import NotebookPlugin as PLUGIN_CLASS
[   68s] spyder_notebook/notebookplugin.py:30: in <module>
[   68s]     from spyder_notebook.widgets.notebooktabwidget import NotebookTabWidget
[   68s] spyder_notebook/widgets/notebooktabwidget.py:30: in <module>
[   68s]     from spyder_notebook.widgets.client import NotebookClient
[   68s] spyder_notebook/widgets/client.py:28: in <module>
[   68s]     from spyder.config.base import get_image_path, get_module_source_path
[   68s] E   ImportError: cannot import name 'get_image_path' from 'spyder.config.base' (/usr/lib/python3.8/site-packages/spyder/config/base.py)
[   68s] ------------------------------- Captured stdout --------------------------------
[   68s] Update LANGUAGE_CODES (inside config/base.py) if a new translation has been added to Spyder
[   68s] ________ ERROR collecting spyder_notebook/widgets/tests/test_client.py _________
[   68s] ImportError while importing test module '/home/abuild/rpmbuild/BUILD/spyder-notebook-0.3.2/spyder_notebook/widgets/tests/test_client.py'.
[   68s] Hint: make sure your test modules/packages have valid Python names.
[   68s] Traceback:
[   68s] /usr/lib64/python3.8/importlib/__init__.py:127: in import_module
[   68s]     return _bootstrap._gcd_import(name[level:], package, level)
[   68s] spyder_notebook/widgets/tests/test_client.py:15: in <module>
[   68s]     from spyder_notebook.widgets.client import NotebookClient
[   68s] spyder_notebook/widgets/client.py:28: in <module>
[   68s]     from spyder.config.base import get_image_path, get_module_source_path
[   68s] E   ImportError: cannot import name 'get_image_path' from 'spyder.config.base' (/usr/lib/python3.8/site-packages/spyder/config/base.py)
[   68s] ___ ERROR collecting spyder_notebook/widgets/tests/test_notebooktabwidget.py ___
[   68s] ImportError while importing test module '/home/abuild/rpmbuild/BUILD/spyder-notebook-0.3.2/spyder_notebook/widgets/tests/test_notebooktabwidget.py'.
[   68s] Hint: make sure your test modules/packages have valid Python names.
[   68s] Traceback:
[   68s] /usr/lib64/python3.8/importlib/__init__.py:127: in import_module
[   68s]     return _bootstrap._gcd_import(name[level:], package, level)
[   68s] spyder_notebook/widgets/tests/test_notebooktabwidget.py:18: in <module>
[   68s]     from spyder_notebook.widgets.notebooktabwidget import (
[   68s] spyder_notebook/widgets/notebooktabwidget.py:30: in <module>
[   68s]     from spyder_notebook.widgets.client import NotebookClient
[   68s] spyder_notebook/widgets/client.py:28: in <module>
[   68s]     from spyder.config.base import get_image_path, get_module_source_path
[   68s] E   ImportError: cannot import name 'get_image_path' from 'spyder.config.base' (/usr/lib/python3.8/site-packages/spyder/config/base.py)
[   68s] =============================== warnings summary ===============================
[   68s] ../../../../../usr/lib/python3.8/site-packages/qdarkstyle/__init__.py:206
[   68s]   /usr/lib/python3.8/site-packages/qdarkstyle/__init__.py:206: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
[   68s]     _logger.warn("No QCoreApplication instance found. "
[   68s] 
[   68s] ../../../../../usr/lib/python3.8/site-packages/notebook/notebookapp.py:50
[   68s]   /usr/lib/python3.8/site-packages/notebook/notebookapp.py:50: DeprecationWarning: zmq.eventloop.ioloop is deprecated in pyzmq 17. pyzmq now works with default tornado and asyncio eventloops.
[   68s]     ioloop.install()
[   68s] 
[   68s] -- Docs: https://docs.pytest.org/en/stable/warnings.html
[   68s] =========================== short test summary info ============================
[   68s] ERROR spyder_notebook/tests/test_config.py
[   68s] ERROR spyder_notebook/tests/test_plugin.py
[   68s] ERROR spyder_notebook/widgets/tests/test_client.py
[   68s] ERROR spyder_notebook/widgets/tests/test_notebooktabwidget.py
```

**Comment by jitseniesen** [comment]
Yes, it is on my to do list.

**Comment by ludwa6** [comment]
Heyall: i only just discovered that spyder-notebook has its own issue tracker; posted [this issue yesterday to the spyder tracker](https://github.com/spyder-ide/spyder/issues/16038) ; that issue is now closed, but it has some info that could be helpful in solving this one, so i'm posting it here, just in case (also so i can be notified of any progress; am very keen for this one :-)

/walt

**Comment by schmoelder** [comment]
Hello everyone,
is there an update on this issue?
Best
Jo

**Comment by ccordoba12** [comment]
Not yet, sorry.

**Comment by drlakecoder** [comment]
any update on when spyder-notebook might start working with spyder-5？ thank you, guys

**Comment by ccordoba12** [comment]
No, sorry. I haven't had time to finish #369.

**Comment by drlakecoder** [comment]
thanks for the update

**Comment by drlakecoder** [comment]
Also, thanks you guys for all the hard work on Spyder. when I am having trouble with other IDEs, I come back to Spyder :). Just made a small contribution through opencollective

**Comment by ccordoba12** [comment]
Thanks for your support @drlakecoder!

**Comment by richlysakowski** [comment]
Any update on Spyder-Notebook working in Spyder 5.1.5?   

I was trying to figure out how to launch Spyder-Notebook programatically from within Spyder Editor, however I could not get Spyder-notebook installed into Spyder 5.1.5.   

Looks like my original goal should work using "from spyder_notebook import open_notebook as spy_nb", and then call "spy_nb.open_notebook(nb_filename)"  

Please let us know when Spyder-notebook is ready for 5.1.5.  Thank you.

**Comment by ccordoba12** [comment]
I'll try to resume the work I started last year in a couple of months, so it should be ready by the end of June at most.

**Comment by dkinneyBU** [comment]
@ccordoba12  I'm a Python developer, but I've never contributed to the Spyder project. I'm happy to help try to get this working if you want me to take a crack at it? I can't make any promises, but I'd be glad to try, just let me know. If you'd rather not, that's ok too. :-)

**Comment by ccordoba12** [comment]
I opened pull request #369 for this, but I haven't had time to finish it.

**Comment by AnisTaluqdar** [comment]
I really want this

**Comment by petrenkonikita112263** [comment]
How long will it take?

**Comment by ccordoba12** [comment]
@petrenkonikita112263, this will be released for sure the second week of July. I already made this plugin to work with Spyder 5 but now I need to make some changes on Spyder for consistency with our new API. And they will be part of the next Spyder version (5.3.2), to be released the first week of July.

**Comment by aspitaleri** [comment]
Following - thanks.

**Comment by foss-fan023** [comment]
> @petrenkonikita112263, this will be released for sure the second week of July. I already made this plugin to work with Spyder 5 but now I need to make some changes on Spyder for consistency with our new API. And they will be part of the next Spyder version (5.3.2), to be released the first week of July.

Any updates on the release? I saw that spyder 5.3.2 was released, but did not see any notebook option so far. Thank you so much for your great work, Spyder is really a unique and perfect tool for data science especially due to the variable explorer!

**Comment by petrenkonikita112263** [comment]
it's the end of first August's week? no new release!?

**Comment by ccordoba12** [comment]
Hey guys, I'm very sorry for the delay. I was busy with other things, but while I was testing PR #369 with Spyder 5.3.2 this week, I found out that that version introduced a bug that we need to solve first before releasing a new Spyder-notebook version.

This means that you'll have to wait until the last week of August for this, when we'll release Spyder 5.3.3. I'm truly sorry for the bad news, but I'm confident this is going to be last delay you'll have to go through.

**Comment by schmoelder** [comment]
Hey Carlos,

No worries, it's good to know that it's almost finished!

I know from experience how difficult it can be to deliver on all the "promises"/schedules. But it's ready when it's ready. It's so important to not put one self under too much pressure. That really kills the joy of working on such a project.

So let me take this opportunity to thank you so much for Spyder, I really appreciate it.

**Comment by idrisschebak-dtsl** [comment]
Hello Carlos, 
I would like to add to Johannes and thank you for what you are doing for this project.

As though i am are very happy to know it's almost finished : it's also very important to not put too much pressure. Spyder is a project that we love, and where people like you infuse their love and passion into. It's a tool that can help save lives (used in Bio research for instance and Economics) but shouldn't put strain into yours for a "promised schedule".

Thank you a lot Carlos for your work on Spyder.

Thank you Johannes for reminding us all about the balance between passion and joy.

**Comment by richlysakowski** [comment]
I second Johannes for his acknowledgement of the importance and
contributions that Carlos Cordoba and his great team make in developing
Spyder.

It is a great tool and is making uncountable (and unknowable) contributions
to the improvement of life in organizations and society around the world.

It would be great if there was a way to measure the specific impact of
particular open source packages, i.e. Spyder.  That is a project for
another day.

Thank you once again for your great contributions !!

Best Regards,

Rich Lysakowski, Ph.D.
Data Scientist, Analytics Engineer,
and Senior Business Analyst
781-640-2048 mobile

**Comment by dkinneyBU** [comment]
@ccordoba12 Just installed Spyder 5.3.3, uninstalled spyder-notebook and re-installed it, and still do not see Notebook in spyder. Does not look like this is fixed. :-(

**Comment by Ali-Flt** [comment]
@dkinneyBU Have you installed from conda? I'm not sure but I don't think the recent changes in [spyder-notebook package](https://anaconda.org/spyder-ide/spyder-notebook) has been registered in to Anaconda yet so we may have to wait for the conda package to get updated. 

I personally would like to know an alternative installation process for the main branch (other than conda) if updating the conda package is gonna take a while.

**Comment by mmagnuski** [comment]
@Ali-Flt, @ccordoba12
If you take a look at the releases tab here you will see that the changes have not been released yet, so they are not present on conda, conda-forge or pypi. If you want to test-drive these changes, you'd have to install spyder-notebook (and likely Spyder too) from master (you can install from github master using pip via `pip install git+...`). Unfortunatelly, I won't be of much more help than pointing the above, as I always install Spyder from conda-forge, so I don't know what dangers await those that install from master. But I'd recommend creating a new conda environment for this.

**Comment by dkinneyBU** [comment]
Ohhhhh, @mmagnuski did not check that, thanks for the education, I actually just did conda install spyder=5.3.3. And yeah, a lightbulb should've gone on when I saw 5.3.0 in Anaconda Navigator (which I did not use, was just checking).

**Comment by ccordoba12** [comment]
Hey guys, I just released a new version of Spyder-notebook (0.4.0) that is compatible with Spyder 5. It's already available to be installed with pip, but please don't use it if you're working with Anaconda. Instead, wait until this version is part of conda-forge by the end of the day/tomorrow, depending on your timezone.

**Comment by ryohei22** [comment]
I installed it through conda and it'working perfectly so far!! I appreciate the release and your work on this! This is amazing! Thank you so much!!

**Comment by edgarduarteforero** [comment]
I had been expecting for this update for some time. Thanks a lot @ccordoba12 . I've installed it using conda in a Windows machine. Working perfectly.

**Comment by mg3146** [comment]
Hi - could you please post instructions on how to install this (using spyder 5.3.3 in a virtual env, all via Anaconda).  Thanks in advance!

**Comment by edgarduarteforero** [comment]
My virtual environment has Spyder 5.3.3, Python 3.10.4 and I simply used `conda install -c conda-forge spyder-notebook` as recommended from [Anaconda](https://anaconda.org/conda-forge/spyder-notebook) to install the package.

**Comment by ccordoba12** [comment]
@mg3146, the solution is to create a new environment and install Spyder-notebook from conda-forge on it (as @edgarduarteforero mentioned).

Note: I'm going to lock this issue so that people subscribed to it don't get spammed by error reports. If you have issues with Spyder-notebook, please open new issues about it.
