### ISSUE TITLE
Installing spyder-notebook reverts the spyder installation from 5.0.0 to 4.2.5, reinstalling spyder 5.0.0, spyder-notebook not present in View>Panes

### ISSUE THREAD

**Issue by AnthonyTheKoala** [spyder-ide/spyder-notebook#361]
I wish to report the following:
Issue: I have spyder 5.0.0
When I install spyder-notebook the following happens:
pip install spyder-notebook
spyder reverts from spyder 5.0.0 to 4.2.5
In spyder 4.2.5 one can see in View > Panes > Notebook.

However when I reinstall spyder 5.0.0:
pip install spyder --upgrade
spyder-notebook is absent from View > Panes.  Notebook is gone - Notebook is absent from items to check.

But if I install spyder-notebook again:
pip install spyder-notebook
Spyder reverts to 4.2.5.

Thank you,
Anthony of Sydney

**Comment by AnthonyTheKoala** [comment]
I apologise, I forgot to add additional information:
Python: Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]
OS: Win 7
Thank you
Anthony of Sydney

**Comment by AnthonyTheKoala** [comment]
I recently changed the version of Python from 
Python: Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]
to
Python: Python 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
OS: Win 7
Thank you
Anthony of Sydney

**Comment by AnthonyTheKoala** [comment]
**Installed latest Spyder 5.0.1 as at 17-04-2021 (2021-17-04)**
BUT
The same problem occurs:

- In Spyder v5.0.1, the Notebook check box from View > Panes is not present
- Install spyder-notebook by pip install -U spyder-notebook --upgrade **BUT** spyder reverts to v4.2.5.
- In Spyder v4.2.5, spyder-notebook can be checked by View > Panes > Notebook (check or uncheck)
- Reinstall Spyder v5.0.1, cannot check spyder-notebook via View>Panes.
Thank you
Anthony of Sydney

**Comment by ccordoba12** [comment]
Hey @AnthonyTheKoala, thanks for reporting. This problem happens because the latest release of Spyder-notebook is not compatible with Spyder 5 yet. And it could take a couple of months to make it compatible, sorry.

**Comment by AnthonyTheKoala** [comment]
Dear Carlos, thank you for your answer. 

Patience is a virtue. 

I love the Spyder Python environment. It is my preferred IDE over all other IDEs. 

Thank you and God Bless You.

Anthony of Sydney

Using google translate to translate from English to Spanish then back to English:
Estimado Carlos, gracias por tu respuesta.

La paciencia es una virtud.

Me encanta el entorno de Spyder Python. Es mi IDE preferido sobre todos los demás IDE.

Gracias y que Dios te bendiga.

Antonio de Sydney

**Comment by ccordoba12** [comment]
Thanks for your kind words @AnthonyTheKoala!

**Comment by jitseniesen** [comment]
Issue #360 is about making the spyder-notebook plugin compatible with Spyder 5. I don't think there is more to discuss here, so I am closing this issue.
