### ISSUE TITLE
line number

### ISSUE THREAD

**Issue by zero19970** [spyder-ide/spyder-notebook#364]
how to show line numbers in spyder-notebook of each cell?

**Comment by rojasgabriel** [comment]
I think that if you press Shift+L or Cntl+L it'll work

**Comment by richlysakowski** [comment]
Shift-L works in Windows 10, but you must press Shift-L while the cell is selected.  It does not work when the cursor is inside a code cell (in Edit mode).  

Could the developers please make the "Line Numbers" command available on the Spyder-Notebook widget's "View" menu?  

```import this "Explicit is better than Implicit"```

I had to come to this github.com page to find out if this function is even available.   Right now this command is mostly hidden.  There is no Help menu or documentation built into Spyder Notebook.  Even just a "User Shortcuts" information pane under the View Menu or the "hamburger menu" in the upper-righthand corner.  Line numbers are needed for debugging.  

I love being able to open Jupyter inside Spyder, without launching an external server.  Keep up the good work guys !!

**Comment by ccordoba12** [comment]
> Could the developers please make the "Line Numbers" command available on the Spyder-Notebook widget's "View" menu?

I'll try to do it before the end of the year, but I can't make promises because we have a lot of other things to do.

> I love being able to open Jupyter inside Spyder, without launching an external server. Keep up the good work guys !!

Thanks for your kind words @richlysakowski!
