### ISSUE TITLE
In HiDpi monitor, UI is small

### ISSUE THREAD

**Issue by jiewangjs** [spyder-ide/spyder-notebook#366]
Anyway to setting scale factor once for all ?
Right now, it is uncomfortable to use in this scenario.

**Comment by ccordoba12** [comment]
Hey @jiewangjs, thanks for reporting. Could you post a screenshot of what you're talking about?

**Comment by ycwang-hello** [comment]
This may be related to #174.

**Comment by ccordoba12** [comment]
Ok, thanks for mentioning that @ycwang-hello. Closing then in favor of #174.
