### ISSUE TITLE
Notebook backend missing 

### ISSUE THREAD

**Issue by mksk4** [spyder-ide/spyder-notebook#370]
## Description of your problem

**What steps will reproduce the problem?**

1.  Add %matplotlib notebook magic
2. Create a plot within a cell

**What is the expected output? What do you see instead?**
Expected output: Interactive plot under the cell.
Actual output: New figure window pops up with the interactive plot.

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**
Inline backend works as expected (under the cell plotting), but with no interactive plots.
When %matplotlib notebook is used, the following warning is produced:

```
Warning: Cannot change to a different GUI toolkit: notebook. Using qt5 instead.
```

The option is also not available in the list under Preferences->IPython Console->Graphics->Graphics Backend

## Versions and main components

* Spyder Version: 4.2.5
* Python Version: 3.9.7
* Qt Version: 5.9.7
* PyQt Version: 5.9.2
* Jupyter Notebook Version: 6.4.6
* Operating system: macOS Monterey 12.0.1

### Mandatory:
applaunchservices >=0.1.7       :  0.2.1 (OK)
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  2.0.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.29.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  23.4.0 (OK)
nbconvert >=4.0                 :  6.1.0 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.10.0 (OK)
pylint >=1.0                    :  2.9.6 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.3 (OK)
qtconsole >=5.0.3               :  5.1.1 (OK)
qtpy >=1.5.0                    :  1.10.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  58.0.4 (OK)
sphinx >=0.6.6                  :  4.2.0 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  22.3.0 (OK)

### Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.5.0 (OK)
numpy >=1.7                     :  1.21.2 (OK)
pandas >=1.1.1                  :  None (NOK)
scipy >=0.17.0                  :  1.7.1 (OK)
sympy >=0.7.3                   :  None (NOK)

### Spyder plugins:
spyder_notebook                 :  0.3.2 (OK)

**Comment by ccordoba12** [comment]
Since Spyder itself can't display plots with that backend and this plugin is in beta state, we don't think it's necessary to add it as an option in our Preferences. Perhaps when this plugin is more stable we'll do it.

About the error you reported, it's an issue between Matplotlib and Spyder that we're trying to solve right now. I think you could work around it by downgrading to Matplotlib 3.2.0 or 3.1.0.

**Comment by ccordoba12** [comment]
Since Spyder itself can't display plots with that backend and this plugin is in beta state, we don't think it's necessary to add it as an option in our Preferences. Perhaps when this plugin is more stable we'll do it.

About the error you reported, it's an issue between Matplotlib and Spyder that we're trying to solve right now. I think you could work around it by downgrading to Matplotlib 3.2.0 or 3.1.0.

**Comment by mksk4** [comment]
Hello @ccordoba12, Thank you for your reply. I appreciate the work you put into the Spyder-notebook extension and I am looking forward for the stable version. I believe interactive in-place (and not as additional pop-up windows) plots are one of the key convenient features the notebooks offer (for me workflow at least), it would be great if that can be an option in the future.

Regarding the warning, downgrading indeed worked.
