### ISSUE TITLE
Spyder-notebook not available in Spyder 5.*

### ISSUE THREAD

**Issue by ashley-betts70** [spyder-ide/spyder-notebook#372]
## Description of your problem

Spyder-notebook isn't currently available in Spyder 5.*. Is there any chance we could get an update when or if the port is likely to happen?

Regards,

Ashley

## Versions and main components

* Spyder Version: 5.*
* Python Version:
* Qt Version:
* PyQt Version:
* Jupyter Notebook Version:
* Operating system:

**Comment by jitseniesen** [comment]
Hi Ashley,

I am planning to pick this up in a week's time. My best guess for when it will be released is towards the end of February. Please follow issue #360 for updates.

Jitse

**Comment by ashley-betts70** [comment]
Cheers, thanks for the update Jitse. Look forward to its release.
