### ISSUE TITLE
spyder-notebook not working on spyder 4.2.0 without error

### ISSUE THREAD

**Issue by Ali-Flt** [spyder-ide/spyder-notebook#375]
## Description of your problem
I've installed all my packages from conda and I'm pretty sure there is no version conflict. But when I open the Notebook tab in spyder the notebooks are fully blank windows. Also when I select "Open Console" for a notebook, I get this pop up error message:
` There is no kernel associated to this notebook`

I also tried with `spyder 4.2.5` but no luck.

Jupyter notebook server info shows that the server is up and running.

Any clue what the problem might be?
Thanks,
Ali

**What steps will reproduce the problem?**

1. Install spyder=4.2.0 from conda -c conda-forge
2. Install spyder-notebook from conda -c spyder-ide
3. Open spyder and open notebook tab

**What is the expected output? What do you see instead?**
I expect to see jupyter notebooks. I see a blank window instead.

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**
![image](https://user-images.githubusercontent.com/60854595/187050963-787f0fc9-0e70-4cc8-8fb6-8a391fcff9c4.png)

## Versions and main components

* Spyder Version: 4.2.0
* Python Version: 3.8.13 
* Qt Version: 5.9.7
* PyQt Version: 5.9.2
* Jupyter Notebook Version: 6.4.12
* Operating system: linux (arch)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

# Mandatory:
atomicwrites >=1.2.0            :  1.4.1 (OK)
chardet >=2.0.0                 :  5.0.0 (OK)
cloudpickle >=0.5.0             :  2.0.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.0.2 (OK)
IPython >=4.0                   :  8.4.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  4.14.0 (OK)
keyring >=17.0.0                :  23.8.2 (OK)
nbconvert >=4.0                 :  6.5.0 (OK)
numpydoc >=0.6.0                :  1.4.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.9.0 (OK)
pygments >=2.0                  :  2.13.0 (OK)
pylint >=1.0                    :  2.15.0 (OK)
pyls >=0.36.1;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.1.1             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.1.1 (OK)
qtconsole >=4.7.7               :  5.3.1 (OK)
qtpy >=1.5.0                    :  2.2.0 (OK)
rtree >=0.8.3                   :  1.0.0 (OK)
setuptools >=39.0.0             :  63.4.1 (OK)
sphinx >=0.6.6                  :  5.1.1 (OK)
spyder_kernels >=1.10.0;<1.11.0 :  1.10.2 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  1.0.2 (OK)
xdg >=0.26                      :  0.28 (OK)
zmq >=17                        :  23.2.1 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.5.2 (OK)
numpy >=1.7                     :  1.23.1 (OK)
pandas >=1.1.1                  :  1.4.3 (OK)
scipy >=0.17.0                  :  1.7.1 (OK)
sympy >=0.7.3                   :  None (NOK)

# Spyder plugins:
spyder_notebook                 :  0.3.2 (OK)

**Comment by ccordoba12** [comment]
Hey @Ali-Flt, thanks for reporting. Unfortunately, we don't support Spyder 4 anymore, so we can't fix errors about it anymore.

However, we're preparing a new version of Spyder-notebook which will be compatible with Spyder 5 (see pull request #369). It'll be ready in the next couple of weeks, so stay tuned.
