### ISSUE TITLE
Connot find spyder_notebook in spyder5 panels

### ISSUE THREAD

**Issue by river7816** [spyder-ide/spyder-notebook#379]
## Description of your problem

**What steps will reproduce the problem?**
1. I download spyder 5.3.3. on the offical website 
2. I install jupyter_notebook with `conda install spyder-notebook -c conda-forge`
3. I cannot find Notebook in the spyder panel. 
4. I have checked the dependencies and there is no spyder_notebook in it. I have also tried import spyder_notebook and there is no error reported only reported 'No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect.' if you need my env details, it is in the attached files. [env.txt](https://github.com/spyder-ide/spyder-notebook/files/9621605/env.txt)
<img width="466" alt="image" src="https://user-images.githubusercontent.com/114122443/191641869-527bcdc8-7c5a-4ec8-8a92-c15fdb81e7db.png">
<img width="836" alt="image" src="https://user-images.githubusercontent.com/114122443/191642193-841997ae-fb6c-404a-8d62-a83f7a29f5f0.png">

5. I have also run `spyder --debug-info verbose` and the results are in [results.txt](https://github.com/spyder-ide/spyder-notebook/files/9622036/results.txt)

6. I guess it is caused by the miniforge enviroment. I changed the defaut python interpreter to `/Users/shinachuan/miniforge3/bin/python3.10` where I installed my spyder_notebook. But I still cannot find jupyter_notebook in panels.
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/114122443/191650390-a9f19f33-763b-407f-b43f-e473daaa47c6.png">

7. When I run `spyder --debug-info verbose`, it automatically opened spyder(python 3.10) [debug mode 3] and I found Notebook in panels which I suppose it is different with the spyder which I installed in my application folder.
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/114122443/191650478-013463a9-ed71-44b8-857c-63d301244d14.png">

## Versions and main components

* Spyder Version: 5.3.3
* Python Version: 3.10.6
* Qt Version:5.15.6
* PyQt Version: 5.15.7
* Jupyter Notebook Version: 1.0.0
* Operating system: Macos Monterey 12.6
* spyder                    5.3.3           
* spyder-kernels            1.10.0                 
* spyder-notebook           0.4.0       

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.0.0 (OK)
cloudpickle >=0.5.0                  :  2.1.0 (OK)
cookiecutter >=1.6.0                 :  2.1.1 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0              :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.14.0 (OK)
keyring >=17.0.0                     :  23.8.2 (OK)
nbconvert >=4.0                      :  7.0.0 (OK)
numpydoc >=0.6.0                     :  1.4.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.1 (OK)
pygments >=2.0                       :  2.13.0 (OK)
pylint >=2.5.0;<3.0                  :  2.15.0 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0                 :  1.5.0 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.3.2;<5.4.0             :  5.3.2 (OK)
qtpy >=2.1.0                         :  2.2.0 (OK)
rtree >=0.9.7                        :  1.0.0 (OK)
setuptools >=49.6.0                  :  65.3.0 (OK)
sphinx >=0.6.6                       :  5.1.1 (OK)
spyder_kernels >=2.3.3;<2.4.0        :  2.3.3 (OK)
textdistance >=4.2.0                 :  4.4.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.1.9 (OK)
zmq >=22.1.0                         :  23.2.1 (OK)

# Optional:
cython >=0.21                        :  0.29.32 (OK)
matplotlib >=3.0.0                   :  3.5.3 (OK)
numpy >=1.7                          :  1.22.4 (OK)
pandas >=1.1.1                       :  1.4.3 (OK)
scipy >=0.17.0                       :  1.9.1 (OK)
sympy >=0.7.3                        :  1.11.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)

**Comment by ccordoba12** [comment]
Hey @river7816, thanks for reporting. You said

> I download spyder 5.3.3. on the offical website

That means you installed Spyder with our official installer for Mac. And we state in the [Readme](https://github.com/spyder-ide/spyder-notebook#installation) of this project:

>> Note: At the moment it is not possible to use this plugin with the [Spyder installers](http://docs.spyder-ide.org/current/installation.html#standalone-installers) for Windows and macOS. We're working to make that a reality in the future.

So you're expecting something that we very clearly state is not possible.

> I install jupyter_notebook with conda install spyder-notebook -c conda-forge

Since you already did this, you can start using Spyder-notebook by closing Spyder and running the following commands in a terminal

    conda activate <env-where-you-installed-spyder-notebook>
    spyder

**Comment by ccordoba12** [comment]
Sorry, I jus saw this

> When I run spyder --debug-info verbose, it automatically opened spyder(python 3.10) [debug mode 3] and I found Notebook in panels which I suppose it is different with the spyder which I installed in my application folder

So you already discovered that you can use Spyder-notebook from your Miniforge installation (which is fine) but not from our Mac app (which is not possible in any way at the moment).

**Comment by river7816** [comment]
tks，It really helped me
