### ISSUE TITLE
Auto-updating DataFrame Variable Viewer

### ISSUE THREAD

**Issue by mg3146** [spyder-ide/spyder-notebook#383]
Hi,

I often use the variable viewer with pandas DataFrames (which it works great with).  Is there a way, after I double-click the dataframe to view it, to leave that window open and have it auto-update when changes have been made to the DataFrame?  That would be super handy!

**Comment by jitseniesen** [comment]
This is unfortunately not possible. It needs to be fixed in Spyder itself and we already have an issue for that: spyder-ide/spyder#4438. Therefore I am closing this issue.
