### ISSUE TITLE
How to install Spyder-notebook for standalone App

### ISSUE THREAD

**Issue by Dongxy1** [spyder-ide/spyder-notebook#389]
## Description of your problem

**What steps will reproduce the problem?**

**1. I install Spyder IDE from the standalone installer
2. How can I add Spyder-notebook?
3.** 

**What is the expected output? What do you see instead?**

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**

## Versions and main components

* **Spyder Version: 5.4.0**
* Python Version:
* Qt Version:
* PyQt Version:
* Jupyter Notebook Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Hey @Dongxy1, thanks for reporting. Unfortunately, that's not possible at the moment (as it's mentioned in [the description](https://github.com/spyder-ide/spyder-notebook#installation) of this project).

However, we're working to make that possible in the future (perhaps at the end of next year).
