### ISSUE TITLE
how-to installation / testing

### ISSUE THREAD

**Issue by epifanio** [spyder-ide/spyder-notebook#39]
Hi, is there any doc/readme I can have a look at, to learn how to install and use this plugin? thanks!

**Comment by ccordoba12** [comment]
Right now this is very sketchy implementation of what we have in mind for a notebook integration within Spyder. It's usable but we don't think it's ready for public consumption yet.

However, we're working to have it ready in a month or month and a half at most. Please be patient :-)

**Comment by epifanio** [comment]
Thanks @ccordoba12 looking fwd for it.

**Comment by dalthviz** [comment]
@ccordoba12 should we improve in some way the README.md to include something more to test in development the plugin or we can close this one?

**Comment by jitseniesen** [comment]
Earlier this week I talked to somebody who was trying out the plugin, and their comments were:
* It is not clear how to use the plugin. They tried to open an IPython notebook (`.ipynb` file) with `File > Open` but that does not work? So a short "How to use" section may be useful
* It is not clear how to contact somebody. Not everybody is familiar with Github!

**Comment by dalthviz** [comment]
Thanks for the feedback @jitseniesen :), maybe we could put the info of the welcome tab in the "How to use" section?:

![imagen](https://user-images.githubusercontent.com/16781833/31254148-1c6a0f1c-a9ed-11e7-9c30-1b8fad356d64.png)
With the contact somebody, should we put the spyder group/forum link in the readme https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!forum/spyderlib/topics ?

Also, should we create an action in the `File` menu something like `Open in the notebook` to make a distinction between the regular open of a file and opening a notebook?

**Comment by jitseniesen** [comment]
> maybe we could put the info of the welcome tab in the "How to use" section?

Are you referring to the welcome tab in the Notebook pane? The problem for this user was that they did not notice the Notebook pane, so I don't think that will help. Maybe add a sentence to the readme on where to find the Notebook pane?

>  With the contact somebody, should we put the spyder group/forum link in the readme 

Yes, I think that's helpful

> Also, should we create an action in the `File` menu something like `Open in the notebook` to make a distinction between the regular open of a file and opening a notebook?

Maybe, but I think it would be better to have `File` > `Open` decide to open notebook files in the notebook plugin and all other files in the editor plugin; cf.  #89: "Right now that requires changes to Spyder itself, while it'd be better for this plugin to register a handler with the Spyder Open action. We should go with the first approach in Spyder 3, but we'd like to implement the second one in Spyder 4."

**Comment by CoderCoderCoder** [comment]
I just found and installed this plugin, but even though I can now open Jupyter files, they are shown in plain text and there is no "Editor / Notebook" switch. Any hints how to get it working? Thanks!!

**Comment by dalthviz** [comment]
Hi @CoderCoderCoder could you see if the notebook is checked in the `View>Panes` menu?

![notebookpane](https://user-images.githubusercontent.com/16781833/31312040-4318903c-ab7f-11e7-8dd9-69da59f4c9fd.png)

**Comment by goanpeca** [comment]
@dalthviz @ccordoba12 maybe we should really use the normal open dialog and if the plugin is installed, we should be able (via some api) to ask the user if they want to open as text or as a notebook. This would really aviod having all this duplicates. We could add an extra thing on the open dialog (but this would require creating a custom Open dialog for each OS) so that we have a checkbox or something that reads, open as text, so that the default is to open as a notebook.

**Comment by akrsrivastava** [comment]
To create a new notebook, something along the lines of File--> New notebook will be helpful . Saw similar functionality on Pycharm.

**Comment by ccordoba12** [comment]
@goanpeca, this is already closed. Please open a new issue to discuss the approach you propose.
