### ISSUE TITLE
Supporting more functions (e.g. "toggle scrolling") of the Jupyter Notebook

### ISSUE THREAD

**Issue by ycwang-hello** [spyder-ide/spyder-notebook#392]
Any plans to support more functions of the Jupyter Notebook? 

Currently, there are only four items, "Edit", "View", "Run" and "kernel", in the menu bar, which is different from the Jupyter Notebook. (By the way, [this example image](https://raw.githubusercontent.com/spyder-ide/spyder-notebook/master/doc/example.gif) in the README.md seems to have full functions of Jupyter Notebook, but I suppose it may be an earlier version.)

For example, I want to enable vertical scrolling for outputs, which can be done using "Cell" -> "All Output" -> "Toggle Scrolling" in the Jupyter Notebook. But I cannot find this function in Spyder Notebook. I think it shall be great to add "Toggle Scrolling" and more functions to Spyder Notebook. 

## Versions and main components

* Spyder Version: 5.3.3
* Jupyter Notebook Version: 0.4.0
* Operating system: Windows 10

**Comment by ccordoba12** [comment]
Hey @ycwang-hello, thanks for your interest in this project. Unfortunately, we're seriously understaffed at the moment, so we don't have time for additional improvements right now.

**Comment by ycwang-hello** [comment]
Yeah, I understand. Thank you so much for developing this project anyway.

**Comment by jitseniesen** [comment]
The current version of Spyder notebook has all the menus from Jupyter except the "File" menu. In particular, Jupyter moved the "toggle scrolling" item to the context menu and it can also be accessed there from Spyder. So I am closing this issue; if there is anything else that is missing please open a new issue.
