### ISSUE TITLE
pandas numpy crash

### ISSUE THREAD

**Issue by heriberto-avelino** [spyder-ide/spyder-notebook#394]
## Description of your problem

**What steps will reproduce the problem?**

1. import pandas
2. his version of pandas is incompatible with numpy < 1.20.3
your numpy version is 1.19.5.
Please upgrade numpy to >= 1.20.3 to use this pandas version
3.  BUT pip list | grep numpy
numpy                    1.24.1

**What is the expected output? What do you see instead?**
**Please provide any additional information below (stack trace, screenshots, a gif, etc)**

## Versions and main components

* Spyder Version: 421
* Python Version:392
* Qt Version:
* PyQt Version:
* Jupyter Notebook Version:
* Operating system: Debian 11

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Hey @heriberto-avelino, I'm sorry but this error has nothing to do with Spyder or Spyder-notebook. It depends on the way you installed Pandas and Numpy.

If you used pip to upgrade those packages in your Linux distribution (with `sudo pip install -U pandas numpy`), then I'm afraid you broke it and now you have to resintall Debian (yes, the entire distribution). And for next time, please avoid doing that and use virtualenvs instead.

If that was not the case, then simply remove the virtualenv you're using and recreate it. That should fix the problem.
