### ISSUE TITLE
Display Spyder's or Jupyter's context menu on right click

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-notebook#401]
This is a follow-up from PR #396. In version 0.4, right clicking brings up Spyder's context menu (with New, Open, Save). After #396, something has changed and right-clicking brings up Jupyter's context menu. 

I am not yet sure what to do about this. All actions in Spyder's context menu can also be performed via the hamburger menu, so we don't lose functionality by displaying Jupyter's context menu. Furthermore, Jupyter's context menu does have some useful stuff in it.

**Comment by ccordoba12** [comment]
> However, at least on my system the menu does not have the "New notebook" and "Open notebook" menu items to which the text on the welcome screen refers, as shown below

This is perhaps a regression when the plugin was migrated to the new API. I think we should address that along with increasing the dependency on Spyder (`>=5.4.3` once it's released) to fix issue #386, and release 0.4.1 with those fixes.

> After PR https://github.com/spyder-ide/spyder-notebook/pull/396, right-click shows the Jupyter context menu instead of the menu with "Zoom in" and "Zoom out"

I think we should keep that menu to maintain consistency with Jupyter notebook. In that way, users that move from regular Jupyter notebook to the Spyder one would encounter the same experience.

**Comment by jitseniesen** [comment]
We decided to stick with the Jupyter context menu, so nothing needs to be done here.
