### ISSUE TITLE
Please add "View... Show Line Numbers" submenu in SpyderNotebook plugin

### ISSUE THREAD

**Issue by richlysakowski** [spyder-ide/spyder-notebook#403]
## Description of your problem

Line Numbers display in SpyderNotebook is possible, but this functionality is hidden.  It is not reliable in Windows 10 Professional (either I press Control-L or Shift-L, which is it??)  I don't remember how to activate it and then searched the issues log here, and tried Ctrl-L and Shft-L and neither worked.)  Do if I have to have notebook cells NOT selected and type Ctrl-L, Shft-L or both? (and do I have to be hopping up and down on my left foot? 8^)).

SpyderNotebook is supposed to be a plugin wrapper around the Jupyter Notebook client, with (nearly) identical functionality.  

Line numbers are essential to use when debugging large programs.  They should be turned on by default, not off.

**What steps will reproduce the problem?**

1) Look for "Show Line Numbers" on the VIEW menu in Jupyter Notebook or Jupyter Lab, and you will NOT find it.   
2) Then look for "Show Line Numbers" on the VIEW menu in SpyderNotebook, and you will NOT find it.   (It is missing from the expected location.)

**What is the expected output? What do you see instead?**

2) Then look for "Show Line Numbers" on the VIEW menu in SpyderNotebook, and you will NOT find it.   (It is missing from the expected location.)

I will try updating to Spyder 5.4.2 and see if that fixes this.   And I will update SymPy and Cython to see if that fixes it.  

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**

![image](https://user-images.githubusercontent.com/9345711/226765435-a031ecfc-8790-40aa-b5a8-f6c9c19758d3.png)

## Versions and main components

* Spyder Version 5.3.3 :
* Python Version 3.9.13:
* Qt Version 5.15.6:
* PyQt Version 5.15.7:
* Jupyter Notebook Version ??  This is Spyder Notebook:
* Operating system Windows 10:

conda list jupyter
# packages in environment at C:\ProgramData\Anaconda3\envs\spyder_terminal:
#
# Name                    Version                   Build  Channel
jupyter_client            7.4.9              pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.0            py39hcbf5309_0    conda-forge
jupyter_server            1.23.6             pyhd8ed1ab_0    conda-forge
jupyterlab                3.4.7              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.15.1             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.6              pyhd8ed1ab_0    conda-forge

![image](https://user-images.githubusercontent.com/9345711/226765744-5313b77d-ce61-490a-975b-1376548434f0.png)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.1.0 (OK)
cloudpickle >=0.5.0                  :  2.2.1 (OK)
cookiecutter >=1.6.0                 :  2.1.1 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.0.2 (OK)
IPython >=7.31.1;<8.0.0              :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.2 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.16.0 (OK)
keyring >=17.0.0                     :  23.13.1 (OK)
nbconvert >=4.0                      :  7.2.9 (OK)
numpydoc >=0.6.0                     :  1.5.0 (OK)
paramiko >=2.4.0                     :  3.1.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.4 (OK)
pygments >=2.0                       :  2.14.0 (OK)
pylint >=2.5.0;<3.0                  :  2.17.0 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0                 :  1.5.0 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.2 (OK)
qtawesome >=1.0.2                    :  1.2.3 (OK)
qtconsole >=5.3.2;<5.4.0             :  5.3.2 (OK)
qtpy >=2.1.0                         :  2.3.0 (OK)
rtree >=0.9.7                        :  1.0.1 (OK)
setuptools >=49.6.0                  :  67.6.0 (OK)
sphinx >=0.6.6                       :  6.1.3 (OK)
spyder_kernels >=2.3.3;<2.4.0        :  2.3.3 (OK)
textdistance >=4.2.0                 :  4.5.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  3.0.0 (OK)
zmq >=22.1.0                         :  25.0.2 (OK)

# Optional:
cython >=0.21                        :  None (NOK)
matplotlib >=3.0.0                   :  3.5.3 (OK)
numpy >=1.7                          :  1.24.2 (OK)
pandas >=1.1.1                       :  1.4.4 (OK)
scipy >=0.17.0                       :  1.10.1 (OK)
sympy >=0.7.3                        :  None (NOK)

# Spyder plugins:
spyder_notebook.notebookplugin 0.4.0 :  0.4.0 (OK)
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)

**Comment by jitseniesen** [comment]
The shortcut for showing line numbers is Shift-L. You need to have the notebook pane active and be in command mode, so that the cursor up/down keys and the J/K keys move from one cell to the next.

If it is easy, we will add the menu item in the next minor release (version 0.4.1) of the spyder-notebook plugin. The plugin is currently based on Jupyter Lab 1, which is quite out of date.

Slightly longer term, we are planning to base the next major release (version 0.5.0) of the Spyder plugin on Jupyter Notebook 7 (which uses Jupyter Lab 4). The intention is that the plugin will be closer to Jupyter Notebook.
