### ISSUE TITLE
Spyder notebook not launching in Spyder

### ISSUE THREAD

**Issue by KaynaL-MT** [spyder-ide/spyder-notebook#418]
## Description of your problem
I have installed spyder-notebook in my conda environment but when I connect to the environment in Spyder, the notebook tab does not appear anywhere (not at the bottom near the editor nor in View > Panes > )

**What steps will reproduce the problem?**
1. In terminal run command: conda install spyder-notebook -c spyder-ide
2. Open spyder3 from terminal

## Versions and main components

* Spyder Version: 5.4.3
* Python Version:  3.10.10
* Qt Version: 5.15.8
* PyQt Version: 2.3.1
* Jupyter Notebook Version: 6.5.4
* Operating system: OSX Ventura 13.3.1 (M1)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.1 (OK)
chardet >=2.0.0                                  :  5.1.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  2.1.1 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.12.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.2 (OK)
jellyfish >=0.7                                  :  0.11.2 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  7.3.0 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.4 (OK)
pygments >=2.0                                   :  2.14.0 (OK)
pylint >=2.5.0,<3.0                              :  2.17.2 (OK)
pylint_venv >=2.1.1                              :  None (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.1 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.3.1 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  67.6.1 (OK)
sphinx >=0.6.6                                   :  5.1.1 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.3 (OK)
textdistance >=4.2.0                             :  4.5.0 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  3.0.0 (OK)
zmq >=22.1.0                                     :  25.0.2 (OK)

# Optional:
cython >=0.21                                    :  0.29.34 (OK)
matplotlib >=3.0.0                               :  3.7.1 (OK)
numpy >=1.7                                      :  1.24.2 (OK)
pandas >=1.1.1                                   :  2.0.0 (OK)
scipy >=0.17.0                                   :  1.10.1 (OK)
sympy >=0.7.3                                    :  1.11.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2             :  1.2.2 (OK)

**Comment by jitseniesen** [comment]
Hello. We do not use the `spyder-ide` channel anymore. You should use the command `conda install spyder-notebook -c conda-forge` to install the plugin.

From what you say, it sounds like you installed Spyder in one environment and then you use a different environment for the Spyder console, as explained in the FAQ ["How do I get Spyder to work with my existing Python packages/environment?"](https://docs.spyder-ide.org/current/faq.html#using-existing-environment). In that case, you need to install the `spyder-notebook` plugin in the same environment as Spyder, and not in the environment that you use for the Spyder console.

I hope this helps you fix the issue. If not, then test whether you can import the plug-in manually by opening a Python console in the same environment as Spyder and typing `import spyder_notebook`. This command should run without errors. Let us know how it is going.

**Comment by jitseniesen** [comment]
Closing due to lack of response.
