### ISSUE TITLE
[I want to translate the program to hebrew]

### ISSUE THREAD

**Issue by seychelles111** [spyder-ide/spyder-notebook#424]
Hiya lads, I would like to translate it to hebrew, and collab with an even greater amount of awesome linguistque's

**Comment by jitseniesen** [comment]
Hi @seychelles111, thanks very much for your kind offer.

To translate Spyder, please go to https://crowdin.com/project/spyder and hopefully the instructions there are clear. Let me know if you need help.

Hebrew would be the first Spyder language that is written from right to left, so it will be interesting to see how it works.
