### ISSUE TITLE
Issue with bibliometrix package

### ISSUE THREAD

**Issue by lkbravo** [spyder-ide/spyder-notebook#425]
## Description of your problem

**What steps will reproduce the problem?**

1. I have run biblioshiny and uploaded a bibliometric database (merging Scopus and WoS databases). Still, when I chose the thematic evolution map, It jumps a mistake: duplicate 'row. names´ are not allowed.

**What is the expected output? What do you see instead?**
It does not generate the thematic evolution map using the author keywords by periods

**Please provide any additional information below (stack trace, screenshots, a gif, etc.)**

![image](https://github.com/spyder-ide/spyder-notebook/assets/136648583/41fa1a1a-bca1-4a86-9acb-fd46cf5a21f2)

## Versions and main components
* RStudio version: 4.0.5
* Spyder Version: 3.7.9
* Python Version:
* Qt Version:
* PyQt Version:
* Jupyter Notebook Version:
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by jitseniesen** [comment]
Hi @lkbravo, I think you have reported this in the wrong place. I do not recognize the program in the screenshot. I searched for biblioshiny and it seems you can ask your question at https://github.com/massimoaria/bibliometrix/issues
