### ISSUE TITLE
Conda installs notebook 7.0.0 but spyder-notebook is not ready yet

### ISSUE THREAD

**Issue by GuillaumeLeGoc** [spyder-ide/spyder-notebook#436]
## Description of your problem

**What steps will reproduce the problem?**

1. Install Spyder and spyder_notebook in a clean conda environment with : 
`conda create -c conda-forge -n spyder-env spyder numpy scipy pandas matplotlib sympy cython spyder-notebook spyder-terminal`
2. Launch Spyder and look for the Notebook pane

**What is the expected output? What do you see instead?**
Notebook pane should be available in View > Panes. It is not.

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**
From the IPython console, when trying to import spyder_notebook, an error is raised : cannot import notebookapp from notebook, in the file utils/servermanager.py.
Comparing this file to the one here in the Github repo, a newer version uses [serverapp from jupyter_server](https://github.com/spyder-ide/spyder-notebook/blob/731a6095f6e0c4335aa2f12f4a033033ab04518f/spyder_notebook/utils/servermanager.py#L22) instead.

Investigating leads me to the fact that when installing spyder and spyder_notebook from scratch, it installs the notebook version 7.0.0, which seems to break the spyder_notebook distributed in conda-forge for now. 

** Fix **
I guess it will be fixed in the next release of this plugin (see this [PR](https://github.com/spyder-ide/spyder-notebook/pull/429). In the meantime, if anyone encounters this issue, downgrading the notebook package to the previous version works. In the environment where Spyder in installed, run : 
`conda install -c conda-forge notebook=6.3`

## Versions and main components

* Spyder Version: 5.4.4
* Python Version: 3.11.4
* Qt Version: 5.15.6
* PyQt Version: 5.15.7
* Jupyter Notebook Version: 0.4.1
* Operating system: Windows 10

### Mandatory:
atomicwrites >=1.2.0                                                        :  1.4.1 (OK)
chardet >=2.0.0                                                             :  5.1.0 (OK)
cloudpickle >=0.5.0                                                         :  2.2.1 (OK)
cookiecutter >=1.6.0                                                        :  2.2.3 (OK)
diff_match_patch >=20181111                                                 :  20230430 (OK)
intervaltree >=3.0.2                                                        :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0,!=8.11.0,!=8.12.0,!=8.12.1 :  8.14.0 (OK)
jedi >=0.17.2,<0.19.0                                                       :  0.18.2 (OK)
jellyfish >=0.7                                                             :  1.0.0 (OK)
jsonschema >=3.2.0                                                          :  4.18.4 (OK)
keyring >=17.0.0                                                            :  24.2.0 (OK)
nbconvert >=4.0                                                             :  7.7.2 (OK)
numpydoc >=0.6.0                                                            :  1.5.0 (OK)
paramiko >=2.4.0                                                            :  3.2.0 (OK)
parso >=0.7.0,<0.9.0                                                        :  0.8.3 (OK)
pexpect >=4.4.0                                                             :  4.8.0 (OK)
pickleshare >=0.4                                                           :  0.7.5 (OK)
psutil >=5.3                                                                :  5.9.5 (OK)
pygments >=2.0                                                              :  2.15.1 (OK)
pylint >=2.5.0,<3.0                                                         :  2.17.4 (OK)
pylint_venv >=3.0.2                                                         :  3.0.2 (OK)
pyls_spyder >=0.4.0                                                         :  0.4.0 (OK)
pylsp >=1.7.4,<1.8.0                                                        :  1.7.4 (OK)
pylsp_black >=1.2.0,<3.0.0                                                  :  1.3.0 (OK)
qdarkstyle >=3.0.2,<3.2.0                                                   :  3.1 (OK)
qstylizer >=0.2.2                                                           :  0.2.2 (OK)
qtawesome >=1.2.1                                                           :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                                                    :  5.4.3 (OK)
qtpy >=2.1.0                                                                :  2.3.1 (OK)
rtree >=0.9.7                                                               :  1.0.1 (OK)
setuptools >=49.6.0                                                         :  68.0.0 (OK)
sphinx >=0.6.6                                                              :  7.0.1 (OK)
spyder_kernels >=2.4.4,<2.5.0                                               :  2.4.4 (OK)
textdistance >=4.2.0                                                        :  4.5.0 (OK)
three_merge >=0.1.1                                                         :  0.1.1 (OK)
watchdog >=0.10.3                                                           :  3.0.0 (OK)
zmq >=22.1.0                                                                :  25.1.0 (OK)

### Optional:
cython >=0.21                                                               :  3.0.0 (OK)
matplotlib >=3.0.0                                                          :  3.7.2 (OK)
numpy >=1.7                                                                 :  1.25.1 (OK)
pandas >=1.1.1                                                              :  2.0.3 (OK)
scipy >=0.17.0                                                              :  1.11.1 (OK)
sympy >=0.7.3                                                               :  1.12 (OK)

### Spyder plugins:
spyder_notebook.notebookplugin 0.4.1                                        :  0.4.1 (OK)
spyder_terminal.terminalplugin 1.2.2                                        :  1.2.2 (OK)

Cheers and good luck for the next release :)

**Comment by jitseniesen** [comment]
Thanks for taking the time for writing this all up. You are completely correct. We should have specified that the plugin only works with (Jupyter) notebook 6.

The next release of the plugin will be available soon (within days, not months).

**Comment by jitseniesen** [comment]
I released version 0.5.1 of the plugin a couple of days ago, which works with Jupyter Notebook 7 (but not Notebook 6), so I am closing this issue.
