### ISSUE TITLE
how to wrap text

### ISSUE THREAD

**Issue by QQLazy** [spyder-ide/spyder-notebook#443]
**What is the expected output? What do you see instead?**
I wonder if the plugin can wrap text and show line numbers as default, which is like the Jupyter lab or notebook.
thanks 

## Versions and main components

* Spyder Version:5.4.3
* Python Version:3.11
* Qt Version:5.15.2
* PyQt Version: qtpy==2.2.0
* Jupyter Notebook Version:6.5.4
* Operating system: macos

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
# Mandatory:
applaunchservices >=0.3.0                        :  0.3.0 (OK)
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  1.7.3 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.15.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  1.0.1 (OK)
jsonschema >=3.2.0                               :  4.19.1 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  6.5.4 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  2.3.0 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.2.0 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  68.0.0 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.4 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
zmq >=22.1.0                                     :  23.2.0 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  3.7.2 (OK)
numpy >=1.7                                      :  1.24.3 (OK)
pandas >=1.1.1                                   :  2.0.3 (OK)
scipy >=0.17.0                                   :  1.11.1 (OK)
sympy >=0.7.3                                    :  1.11.1 (OK)

# Spyder plugins:
spyder_notebook.notebookplugin 0.4.1             :  0.4.1 (OK)

**Comment by jitseniesen** [comment]
Hi @QQLazy , I believe the latest version can do this. You have version 0.4.1 of the spyder-notebook plugin installed, but the latest version is 0.5.1. If you use conda, you can upgrade to this version with the command
```
conda install -c conda-forge spyder-notebook=0.5.1
```
Please be aware that this wll also upgrade Jupyter Notebook to version 7 and Jupyter Lab to version 4.

I hope this helps, do let me know if you have any further questions.

**Comment by QQLazy** [comment]
thanks for the help, I updated the package but found the "wrap words" in the "view" menu is gray.
the new version of Jupyter-lab and notebook be the same...


![image](https://github.com/spyder-ide/spyder-notebook/assets/63276181/cdecddd1-2e4b-4b88-a80a-c279fa04ef7f)

**Comment by QQLazy** [comment]
I think I find the way to solve it, one can enter into the Jupyter lab, and follow the path below:
`Settings -> Setting Editors -> JSON Settings Editor -> MODIFIED -> Notebook `, and edit the `User Preferences`.

**Comment by jitseniesen** [comment]
Thanks for sharing your solution, I am glad that you found a way to resolve the issue for you.
