### ISSUE TITLE
Add a file switcher instance to this plugin

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-notebook#45]
It'd be really nice to have it to switch among notebooks.

@goanpeca, question: `Ctrl+P` (the shortcut to call the switcher) is a global one right now, but I think we should use the same one here. So what do you think we should do to make that work?

Possibilities:

1. Make `Ctrl+P` a plugin shortcut. Cons: Not nice because you'd have to give focus to the Editor or the notebook to make it work.
2. Make `Ctrl+P` to detect the current plugin and change its behavior accordingly.
3. Add an API for the file switcher so external plugins can register with it.

**Comment by goanpeca** [comment]
Well probably 3, I gues?

**Comment by ccordoba12** [comment]
I think notebook. It'd less confusing, right?

**Comment by goanpeca** [comment]
Sure :+1:
