### ISSUE TITLE
Do Help pane integrated with Notebook plugin?

### ISSUE THREAD

**Issue by satyrmipt** [spyder-ide/spyder-notebook#452]
## Description of your problem

**What steps will reproduce the problem?**

Can not activate help display for any function in help pane while working in notebook.
All buttons in Tools - Preferences - Help are activated.
Tools - Preferences - Notebook has no additional options about help display

**What is the expected output? What do you see instead?**

Ordinary Spyder has help pane and you can activate help display when you press ctrl+I on the function in Editor.
But spyder notebook show nothing on ctrl+I.

Please inform is it bug on my side or this feature not developed yet in spyder notebook.

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**

help display (ctrl+I) works well for Editor. Also it works if i print function name directly in help pane Object field.
Source menu of help pane has two options - Editor and Console. No "Notebook" option there

## Versions and main components

* Spyder Version: 5.4.3 (conda)
* Python Version: 3.11.5 64-bit
* Qt Version: 5.15.2
* PyQt Version: 5.15.7
* Jupyter Notebook Version: 7.0.7
* Operating system: Windows 10 

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

# Mandatory:
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  1.7.3 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.15.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  1.0.1 (OK)
jsonschema >=3.2.0                               :  4.21.1 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  6.5.4 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  2.3.0 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.2.0 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  68.0.0 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.4 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
zmq >=22.1.0                                     :  24.0.1 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  3.7.2 (OK)
numpy >=1.7                                      :  1.24.3 (OK)
pandas >=1.1.1                                   :  2.0.3 (OK)
scipy >=0.17.0                                   :  1.11.1 (OK)
sympy >=0.7.3                                    :  1.11.1 (OK)

# Spyder plugins:
spyder_notebook.notebookplugin 0.5.1             :  0.5.1 (OK)

**Comment by ccordoba12** [comment]
Hey @satyrmipt, thanks for reporting. Unfortunately, the Help pane is not connected to Spyder-notebook at the moment.

However, this is a very interesting idea, so we'll try to see if we can make that happen in the future.

**Comment by jitseniesen** [comment]
I am merging this with issue #257 which is basically the same.
