### ISSUE TITLE
View > Pane > Notebook not showing, but it was today, before some updates

### ISSUE THREAD

**Issue by sancho-s** [spyder-ide/spyder-notebook#463]
## Description of your problem

**What steps will reproduce the problem?**

1. Launch spyder
2. View > Panes > (No Notebook)

**What is the expected output? What do you see instead?**
Being able to select Notebook, but I can't.

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**

Spyder notebook was working fine today.
I made a few updates, and now it does not show.
Useful info:
```
(analysis) > conda list | findstr spyder
pyls-spyder               0.4.0              pyhd3eb1b0_0    defaults
spyder                    5.5.1           py312haa95532_3    defaults
spyder-kernels            2.5.0           py312haa95532_0    defaults
spyder-notebook           0.1.4                      py_0    spyder-ide

(analysis) > spyder
fromIccProfile: failed minimal tag size sanity
C:\Users\User1\Anaconda\envs\analysis\Lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated and will be removed in a future release
  "class": algorithms.Blowfish,
C:\Users\User1\Anaconda\envs\analysis\Lib\site-packages\jupyter_client\threaded.py:73: RuntimeWarning: ZMQStream only supports the base zmq.Socket class.

                Use zmq.Socket(shadow=other_socket)
                or `ctx.socket(zmq.DEALER, socket_class=zmq.Socket)`
                to create a base zmq.Socket object,
                no matter what other kind of socket your Context creates.

  self.stream = zmqstream.ZMQStream(self.socket, self.ioloop)
C:\Users\User1\Anaconda\envs\analysis\Lib\site-packages\jupyter_client\threaded.py:73: RuntimeWarning: ZMQStream only supports the base zmq.Socket class.

                Use zmq.Socket(shadow=other_socket)
                or `ctx.socket(zmq.SUB, socket_class=zmq.Socket)`
                to create a base zmq.Socket object,
                no matter what other kind of socket your Context creates.

  self.stream = zmqstream.ZMQStream(self.socket, self.ioloop)

(analysis) > conda list | findstr qt
pyqt                      5.15.10         py312hd77b12b_0    defaults
pyqt5-sip                 12.13.0         py312h2bbff1b_0    defaults
pyqtwebengine             5.15.10         py312hd77b12b_0    defaults
qt-main                   5.15.2              h19c9488_10    defaults
qt-webengine              5.15.9               h5bd16bc_7    defaults
qtawesome                 1.2.2           py312haa95532_0    defaults
qtconsole                 5.5.1           py312haa95532_0    defaults
qtpy                      2.4.1           py312haa95532_0    defaults
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0    defaults
```

**Related:**
1. https://stackoverflow.com/questions/69214176/jupyter-notebook-view-missing-in-spyder-ide-even-after-install
2. https://github.com/spyder-ide/spyder-notebook/issues/146

## Versions and main components

* Spyder Version: 5.5.1
* Python Version: 3.12.4
* Qt Version: 5.15.2
* PyQt Version: 5.15.10
* Jupyter Notebook Version: 6.5.7
* Operating system: Win 11

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

# Mandatory:
atomicwrites >=1.2.0             :  1.4.0 (OK)
chardet >=2.0.0                  :  4.0.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20200713 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.25.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.0.1 (OK)
jsonschema >=3.2.0               :  4.19.2 (OK)
keyring >=17.0.0                 :  24.3.1 (OK)
nbconvert >=4.0                  :  7.10.0 (OK)
numpydoc >=0.6.0                 :  1.7.0 (OK)
paramiko >=2.4.0                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.0 (OK)
pygments >=2.0                   :  2.15.1 (OK)
pylint >=2.5.0,<3.1              :  2.16.2 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.10.0,<1.11.0           :  1.10.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.2.1                :  1.2.2 (OK)
qtconsole >=5.5.1,<5.6.0         :  5.5.1 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.0.1 (OK)
setuptools >=49.6.0              :  69.5.1 (OK)
sphinx >=0.6.6                   :  7.3.7 (OK)
spyder_kernels >=2.5.0,<2.6.0    :  2.5.0 (OK)
textdistance >=4.2.0             :  4.2.1 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  4.0.1 (OK)
zmq >=22.1.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  3.8.4 (OK)
numpy >=1.7                      :  1.26.4 (OK)
pandas >=1.1.1                   :  2.2.2 (OK)
scipy >=0.17.0                   :  1.13.1 (OK)
sympy >=0.7.3                    :  1.12 (OK)

**Comment by sancho-s** [comment]
Dear Jitse,
Is there any way to install spyder from conda-forge, and then
spyder-notebook, in the same environment?
It has all the functionality I need.
Thanks.

**Comment by jitseniesen** [comment]
@sancho-s I am not sure I understand what you are asking.

What I suggested will get you spyder and spyder-notebook from conda-forge in the same environment, without touching your current environment (which I think is called `analysis`). You can then tell spyder to use the `analysis` environment to run your Python code and everything should work. That is the safest procedure.

If you want to have everything in one environment, you have to get all your packages from conda-forge and re-install all the packages you have now.

Installing conda-forge packages in your current environment is very likely to lead to problems, which may be subtle or only surface after you install or upgrade an unrelated package, and the only way to resolve this is to re-install everything.

**Comment by jitseniesen** [comment]
I hope you managed to solve the issue with the answers given.

I also deleted the spyder-notebook 0.1.x packages from the spyder-ide channel, because these did not have an upper limit on the Spyder dependency, but they don't work with Spyder 4 and later.

I will close the issue, but if you do have any further questions, feel free to raise them.
