### ISSUE TITLE
Include Jupyter Notebook version 7.2.1

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-notebook#464]
[Jupyter Notebook v7.2.1](https://github.com/jupyter/notebook/releases/v7.2.1) was releases on 7 June and includes some bug fixes and other goodies.

**Comment by Uriel8888what** [comment]
Hi, i wonder if i could change the kernel of spyder notebook to my conda environment! I could not find my conda environment. It shows that i could only choose the kernel of "Python 3 (spyder)". Thanks for you kindly answer!

**Comment by ccordoba12** [comment]
@Uriel8888what, that's not possible at the moment but it's a very interesting idea!

Could you open a new issue about so we don't forget to address it in another release? Thanks!
