### ISSUE TITLE
Not able to use spyder-notebook with spyder 6.0.0

### ISSUE THREAD

**Issue by KunalSukhija-Fareye** [spyder-ide/spyder-notebook#468]
## Description of your problem

**What steps will reproduce the problem?**

1. update the standalone spyder to spyder 6.0.0
2. in the console run pip install spyder-notebook

**What is the expected output? What do you see instead?**
Expected spyder-notebook plugin to be installed and work fine
issue is it deprecates spyder to 5.5.6

## Versions and main components

* Spyder Version:6.0.0
* Python Version:3.11.9
* Qt Version:
* PyQt Version:
* Jupyter Notebook Version:
* Operating system: Ubuntu

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by jitseniesen** [comment]
There is now a new version of the plugin that is compatible with Spyder 6, so I am closing this issue.

However, if you use the standalone installer, then it is not possible to add plugins like this notebook plugin.
