### ISSUE TITLE
Write a test to check that Spyder's preferences work

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-notebook#472]
Write a test which would have caught the embarrassing bug in #470. We do have one test which opens the notebook preferences page, but that did not catch the bug, so investigate.

**Comment by ccordoba12** [comment]
For that you can take a look at `spyder/plugins/preferences/tests/conftest.py`. The `config_dialog` fixture allows to test config pages in the Preferences dialog, as it's done in `spyder/plugins/pylint/tests/test_pylint_config_dialog.py`, for instance.
