### ISSUE TITLE
Spyder-Notebook not Showing up

### ISSUE THREAD

**Issue by tdhampson12** [spyder-ide/spyder-notebook#479]
## Description of your problem
I originally installed Spyder from an executable, then I deleted it and reinstalled from Conda by following [https://docs.spyder-ide.org/current/installation.html](url)

I created a conda environment and installed spyder-notebook by following [https://docs.spyder-ide.org/current/plugins/notebook.html ](URL).

I restarted Spyder and the notebook tab does not show up in View --> Panes

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**
<img width="1540" alt="image" src="https://github.com/user-attachments/assets/3606c47b-0685-4f9e-82f3-26abd0a58a0e">

## Versions and main components

* Spyder Version: 6.0.2
* Python Version (in conda): 3.10.15
* Python Version (in Spyder-->About): 3.11.10
* Qt Version: 5.15.8
* PyQt Version: 5.15.9
* Spyder-notebook version: 0.6.1 (spyder-notebook package)
* Jupyter Notebook versions:
<img width="545" alt="image" src="https://github.com/user-attachments/assets/723fd329-0524-4262-921b-25cb9e77fc1e">

* Operating system: * MacOS 14.6.1

## Dependencies

# Mandatory:
aiohttp >=3.9.3                  :  3.10.10 (OK)
asyncssh >=2.14.0,<3.0.0         :  2.18.0 (OK)
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.1.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20241021 (OK)
github >=2.3.0                   :  2.4.0 (OK)
importlib_metadata >=4.6.0       :  8.5.0 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.29.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.1.0 (OK)
jsonschema >=3.2.0               :  4.23.0 (OK)
keyring >=17.0.0                 :  25.5.0 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.8.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.4 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  6.1.0 (OK)
pygments >=2.0                   :  2.18.0 (OK)
pylint >=3.1,<4                  :  3.3.1 (OK)
pylint_venv >=3.0.2              :  3.0.4 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.6.1,<5.7.0         :  5.6.1 (OK)
qtpy >=2.4.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.3.0 (OK)
setuptools >=49.6.0              :  75.3.0 (OK)
sphinx >=0.6.6                   :  8.1.3 (OK)
spyder_kernels >=3.0.1,<3.1.0    :  3.0.1 (OK)
superqt >=0.6.2,<1.0.0           :  0.6.7 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  5.0.3 (OK)
yarl >=1.9.4                     :  1.16.0 (OK)
zmq >=24.0.0                     :  26.2.0 (OK)

# Optional:
cython >=0.21                    :  3.0.11 (OK)
matplotlib >=3.0.0               :  3.9.2 (OK)
numpy >=1.7                      :  2.1.2 (OK)
pandas >=1.1.1                   :  2.2.3 (OK)
scipy >=0.17.0                   :  1.14.1 (OK)
sympy >=0.7.3                    :  1.13.3 (OK)

**Comment by jitseniesen** [comment]
Hi @tdhampson12 . You need to install spyder-notebook in the same conda environment as spyder itself. Can you please check this? From your report, it seems that you might have installed it in the conda environment that you created after installing Spyder.

**Comment by tdhampson12** [comment]
Ah yes! I had been installing it on a separate conda environment. Thank you!
