### ISSUE TITLE
Release 0.1

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder-notebook#51]

**Comment by RoyiAvital** [comment]
Saw Carlos Cordoba @ccordoba12 video on YouTube:

https://www.youtube.com/watch?v=Hf07PmwQwPQ

Really exciting stuff to see guys.
Well Done!

**Comment by ccordoba12** [comment]
@RoyiAvital, thanks for your kind words! We'll release 0.1 this week for sure :-)
