### ISSUE TITLE
Add Jupyter Trove classifier

### ISSUE THREAD

**Issue by rlaverde** [spyder-ide/spyder-notebook#52]
A new trove classifier has been added for ipython related packages, I'm not sure but maybe It could be added to the classifiers of this package

`Framework :: Jupyter`

https://github.com/pypa/pypi-legacy/issues/210#issuecomment-29235093

**Comment by ccordoba12** [comment]
Thanks @rlaverde, you're right about it.

@dalthviz, please add it to our `setup.py`
