### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-notebook#56]
Now that we are very close to release 0.1, I think it's time to update our Readme with a simple description and a couple of screenshots.

@dalthviz, please take care of this one. You can take as inspiration:

https://github.com/spyder-ide/spyder-terminal/blob/master/README.md

but please leave the warning about this not being ready until we release 0.1. I'll remove that warning when we actually do the release.

**Comment by goanpeca** [comment]
You can use http://www.cockos.com/licecap/ to make the animated gif

**Comment by ccordoba12** [comment]
@dalthviz, this is the last pending issue for 0.1, yay!
