### ISSUE TITLE
Add ellipsis to shortened notebook names

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-notebook#66]
I called this notebook "Hola mundo como vas el dia de hoy.ipynb" and this is how it's shown right now

![seleccion_003](https://cloud.githubusercontent.com/assets/365293/26269314/44906190-3cb9-11e7-9470-9edeb51aed79.png)

I propose

1. it should be shown as

        Hola mundo como ...

2. We should remove `.ipynb` from the notebook name. So instead of `foo.ipynb` we should show only `foo`. All notebooks have the `ipynb` extension, so there's no need to show it.
3. We should increase the max number of characters to show to **20** (instead of 15, the current limit).

**Comment by ccordoba12** [comment]
@dalthviz, please work on this one.

**Comment by goanpeca** [comment]
Maybe elide in thw middle instead of the end?

**Comment by ccordoba12** [comment]
But how do we decide where to break? I think it's just simpler (for now) to count 20 chars from the beginning and the ellipsis there.

**Comment by goanpeca** [comment]
Qt offers elide functions on qlabel and font metrics. We could use those and elide on the middle, no ?  'Hola ... el dia de hoy' ?

**Comment by ccordoba12** [comment]
Ups, didn't know that. Then we should use those functions instead :-)

**Comment by goanpeca** [comment]
You can use like this :-)

```python
label = QLabel('Whatever')
css = 'QLabel {font: ...;}'
label.setStyleSheet(css)  # Here define CSS if you want to change font size etc...
fm = self.label_prefix.fontMetrics()
elided_text = fm.elidedText('Hola mundo como vas el dia de hoy', Qt.ElideLeft, 300)
elided_text = fm.elidedText('Hola mundo como vas el dia de hoy', Qt.ElideMiddle, 300)
elided_text = fm.elidedText('Hola mundo como vas el dia de hoy', Qt.ElideRight, 300)
```
