### ISSUE TITLE
Conda nor pip has spyder-notebook in their directory

### ISSUE THREAD

**Issue by michaelbasca** [spyder-ide/spyder-notebook#90]
```
$ conda install spyder-notebook -c spyder-ide
Fetching package metadata ...........

PackageNotFoundError: Package missing in current osx-64 channels:
  - spyder-notebook

Close matches found; did you mean one of these?

    spyder-notebook: ipython-notebook
```

```
$ pip install spyder-notebook
Collecting spyder-notebook
  Could not find a version that satisfies the requirement spyder-notebook (from versions: )
```

When I search the pip directory using spyder as the search term spyder-notebook does not appear.

[https://pypi.python.org/pypi?%3Aaction=search&term=spyder&submit=search](https://pypi.python.org/pypi?%3Aaction=search&term=spyder&submit=search)

**Comment by ccordoba12** [comment]
There's no public release of this package yet. We hope to have our first release the next week.
