### ISSUE TITLE
How to open notebooks after a failed (because slow) server start?

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-notebook#93]
@stonebig commented on [Sat Jul 29 2017](https://github.com/spyder-ide/spyder/issues/4858)

 at first slow start, I get a syder-notebook time-out.
![spyder_notebook_slow_start](https://user-images.githubusercontent.com/4312421/28748141-f66ab93c-74af-11e7-88fa-72d4389122b4.PNG)

Then, even if i ask Display->Notebook, I get a grey window and don't know how to relaunch the spyder-notebook process . Is there a way ? if not, could there be ?

---

@ccordoba12 commented on [Sat Jul 29 2017](https://github.com/spyder-ide/spyder/issues/4858#issuecomment-318860680)

@stonebig, please open issues about each plugin in its corresponding repo instead of here.

**Comment by ccordoba12** [comment]
We can simply increase our time limit to wait until the server is up.

How much time is good enough for you?

**Comment by dalthviz** [comment]
Also maybe you could try to open a new notebook (right-click):

![notebook](https://user-images.githubusercontent.com/16781833/28748321-50d9a26a-747a-11e7-99cc-5e75a5c06c80.png)

This action should attempt again to run the notebook server or connect to one already running.

**Comment by stonebig** [comment]
the pc is old and was compiling, so I can't say it's a normal situation. Having an obvious way to restart would be nice: 
for example, replacing the grey zone per a "click here to start a new notebook" .

**Comment by stonebig** [comment]
"open a new notebook" works, thank you.

I did again have the spyder-Notebook starting timeout, when starting a newly baked winpython. There were also 13 "Kernel died, restarting"on the Spyder Ipython Console during that same Spyder (slow) launch,
