### ISSUE TITLE
Packages missing in current channels

### ISSUE THREAD

**Issue by jhacsonmeza** [spyder-ide/spyder-notebook#94]
I'm very new in this and I don't know what is my problem really.
I installed anaconda with python 3.6 and I'm trying install Spyder notebook plugin opening a Anaconda Promt and writting `conda install spyder-notebook -c spyder-ide` but I get the following:
![error](https://user-images.githubusercontent.com/29784391/28762529-050918b2-757d-11e7-8692-cc749bc9a08a.png)
I'd appreciate your help.

**Comment by dalthviz** [comment]
Hi @jhacsonmeza there's no public release yet. We hope to have our first release soon. You can see if we already have done the release in the future checking [here](https://github.com/spyder-ide/spyder-notebook/releases)

**Comment by jhacsonmeza** [comment]
Thank you very much for the clarification.

**Comment by utsavkesharwani** [comment]
Trying to install on Mac OSX, but getting following error:
```zsh
conda install spyder-notebook -c spyder-ide
Fetching package metadata .........
Solving package specifications: .
PackageNotFoundError: Package not found: '' Package missing in current osx-64 channels:
  - spyder-notebook
```

**Comment by ccordoba12** [comment]
We haven't still created conda packages for this. We're working on it.
