### ISSUE TITLE
problem with the install

### ISSUE THREAD

**Issue by boazdori** [spyder-ide/spyder-notebook#96]
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\user>conda install spyder-notebook -c spyder-ide
Fetching package metadata .................

PackageNotFoundError: Packages missing in current channels:

  - spyder-notebook

We have searched for the packages in the following channels:

  - https://conda.anaconda.org/spyder-ide/win-64
  - https://conda.anaconda.org/spyder-ide/noarch
  - https://conda.anaconda.org/r/win-64
  - https://conda.anaconda.org/r/noarch
  - https://conda.anaconda.org/anaconda-fusion/win-64
  - https://conda.anaconda.org/anaconda-fusion/noarch
  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch

i have spyder 3.2 and notebook 5 installed

**Comment by ccordoba12** [comment]
Sorry but we haven't released spyder-notebook yet.

We'll do it this weekend, thanks for your patience.
